using System;
using System.Linq;
using System.IO;
namespace Touchfish {
public partial class PanelWindow {
 void VerifyAuras(string folder){int before=checks;Check(AuraRules.Ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"All registered persistent aura cards supported");
  var g=MatchFixture();var body=g.Summon(0,"VAN_CS2_182");var champion=g.Summon(0,"VAN_CS2_222");var other=g.Summon(1,"VAN_CS2_182");Check(g.AttackValue(body)==5&&body.MaxHealth==6&&body.Health==6&&champion.MaxHealth==6&&other.Health==5,"Stormwind buffs other friendly units only");g.Damage(new MatchTarget(0,body.Id),5);g.Silence(new MatchTarget(0,champion.Id));Check(body.Health==1&&body.MaxHealth==5&&g.AttackValue(body)==4,"Lost health aura clamps wounded current health without killing");g.Cleanup();Check(g.Players[0].Board.Contains(body),"Aura removal keeps surviving wounded unit");var second=g.Summon(0,"VAN_CS2_222");Check(body.Health==2&&body.MaxHealth==6,"New health aura adds health to injured minion");g.Silence(new MatchTarget(0,body.Id));Check(body.MaxHealth==6&&g.AttackValue(body)==5,"Silenced recipient still receives external aura");g.ReturnToHand(new MatchTarget(0,second.Id));Check(body.MaxHealth==5&&g.AttackValue(body)==4,"Returned source removes aura");
  g=MatchFixture();body=g.Summon(0,"VAN_CS2_182");champion=g.Summon(0,"VAN_CS2_222");second=g.Summon(0,"VAN_CS2_222");Check(body.MaxHealth==7&&g.AttackValue(body)==6&&champion.MaxHealth==7,"Multiple champions stack and buff each other");champion.DamageTaken=champion.MaxHealth;g.Cleanup();Check(body.MaxHealth==6&&second.MaxHealth==6,"Dead source removed before aura refresh");g.Transform(new MatchTarget(0,second.Id),"VAN_CS2_tk1");Check(body.MaxHealth==5&&g.AttackValue(body)==4,"Transform removes source aura");
  g=MatchFixture();body=g.Summon(0,"VAN_CS2_182");g.Summon(0,"VAN_CS2_222");g.SetHealth(new MatchTarget(0,body.Id),1);Check(body.MaxHealth==1&&body.Health==1,"Set-health effect accounts for current health aura");g.Summon(0,"VAN_CS2_222");Check(body.MaxHealth==2,"A later health aura buffs set-health recipient normally");
  g=MatchFixture("SHAMAN");var left=g.Summon(0,"VAN_CS2_182");var totem=g.Summon(0,"VAN_EX1_565");var right=g.Summon(0,"VAN_CS2_182");body=g.Summon(0,"VAN_CS2_182");Check(g.AttackValue(left)==6&&g.AttackValue(right)==6&&g.AttackValue(body)==4,"Flametongue only affects adjacent units");var token=g.Summon(0,"VAN_CS2_231",2);Check(g.AttackValue(token)==3&&g.AttackValue(right)==4,"Insertion immediately moves adjacency aura");g.ReturnToHand(new MatchTarget(0,token.Id));Check(g.AttackValue(right)==6,"Removing neighbor restores adjacency");g.Silence(new MatchTarget(0,totem.Id));Check(g.AttackValue(left)==4&&g.AttackValue(right)==4,"Silenced totem removes both bonuses");
  g=MatchFixture();var scout=g.Summon(0,"VAN_EX1_506a");var foe=g.Summon(1,"VAN_EX1_506a");var leader=g.Summon(0,"VAN_EX1_507");Check(g.AttackValue(scout)==3&&g.AttackValue(foe)==3&&scout.MaxHealth==2&&foe.MaxHealth==2&&leader.MaxHealth==3,"Frozen Warleader buffs all other Murlocs on both boards");var oracle=g.Summon(1,"VAN_EX1_508");Check(g.AttackValue(scout)==4&&g.AttackValue(leader)==4&&g.AttackValue(oracle)==3,"Cross-board Murloc attack auras stack");g.Silence(new MatchTarget(0,leader.Id));Check(scout.MaxHealth==1&&foe.MaxHealth==1,"Warleader silence removes both health auras");
  g=MatchFixture();var friendlyMurloc=g.Summon(0,"VAN_EX1_506a");var enemyMurloc=g.Summon(1,"VAN_EX1_506a");int seerCard=Inject(g,"EX1_103");Check(g.Play(0,seerCard).Success&&friendlyMurloc.MaxHealth==3&&enemyMurloc.MaxHealth==3,"Coldlight Seer battlecry buffs existing other Murlocs on both boards");var seer=g.Players[0].Board.Last();g.Silence(new MatchTarget(0,seer.Id));Check(friendlyMurloc.MaxHealth==3&&enemyMurloc.MaxHealth==3,"Silencing Seer leaves granted health buffs intact");var later=g.Summon(1,"VAN_EX1_506a");Check(later.MaxHealth==1,"Murlocs summoned after Seer receive no retroactive buff");g.ReturnToHand(new MatchTarget(0,seer.Id));Check(friendlyMurloc.MaxHealth==3,"Removing Seer preserves battlecry buff");g.Silence(new MatchTarget(0,friendlyMurloc.Id));Check(friendlyMurloc.MaxHealth==1,"Recipient silence removes Seer enchantment");
  g=MatchFixture();var murkEye=g.Summon(0,"VAN_EX1_062");var friendlyFish=g.Summon(0,"VAN_EX1_506a");var enemyFish=g.Summon(1,"VAN_EX1_506a");Check(g.HasCharge(murkEye)&&g.AttackValue(murkEye)==4&&g.Attack(0,murkEye.Id,new MatchTarget(1)).Success&&g.Players[1].Health==26,"Old Murk-Eye has Charge and gains attack for every other Murloc on both boards");enemyFish.DamageTaken=enemyFish.MaxHealth;g.Cleanup();Check(g.AttackValue(murkEye)==3,"Old Murk-Eye attack updates when another Murloc dies");g.Silence(new MatchTarget(0,murkEye.Id));Check(g.AttackValue(murkEye)==2&&!g.HasCharge(murkEye),"Silence removes Old Murk-Eye's attack aura and Charge");
  g=MatchFixture();var pirate=g.Summon(0,"VAN_NEW1_027");second=g.Summon(0,"VAN_NEW1_027");foe=g.Summon(1,"VAN_NEW1_027");body=g.Summon(0,"VAN_CS2_182");Check(g.AttackValue(pirate)==4&&pirate.MaxHealth==4&&foe.MaxHealth==3&&body.MaxHealth==5,"Captains buff friendly other Pirates only");
  g=MatchFixture("HUNTER");var rhino=g.Summon(0,"VAN_DS1_178");var beast=g.Summon(0,"VAN_CS2_boar");body=g.Summon(0,"VAN_CS2_182");Check(g.HasCharge(rhino)&&g.HasCharge(beast)&&!g.HasCharge(body)&&g.Attack(0,beast.Id,new MatchTarget(1)).Success,"Rhino grants charge to itself and friendly Beasts only");g.Silence(new MatchTarget(0,beast.Id));Check(g.HasCharge(beast),"Recipient silence does not remove external charge");g.Silence(new MatchTarget(0,rhino.Id));beast.AttacksUsed=0;Check(!g.HasCharge(beast)&&!g.Attack(0,beast.Id,new MatchTarget(1)).Success,"Removing Rhino stops same-turn aura charge attacks");
  g=MatchFixture();var apprentice=g.Summon(0,"VAN_EX1_608");var fire=g.Card("VAN_CS2_029");Check(g.CardCost(0,fire)==3&&g.CardCost(1,fire)==4,"Apprentice lowers own spells only");g.Summon(0,"VAN_EX1_608");Check(g.CardCost(0,fire)==2,"Spell reducers stack");int hand=Inject(g,"CS2_029");g.Players[0].Mana=2;Check(g.Play(0,hand,new MatchTarget(1)).Success&&g.Players[0].Mana==0,"Engine spends effective spell cost");g.Silence(new MatchTarget(0,apprentice.Id));Check(g.CardCost(0,fire)==3,"Silence removes spell reduction");
  g=MatchFixture();var wraith=g.Summon(0,"VAN_EX1_616");var minion=g.Card("VAN_CS2_182");Check(g.CardCost(0,minion)==5&&g.CardCost(1,minion)==5,"Mana Wraith taxes both players");g.Summon(0,"VAN_CS2_227");Check(g.CardCost(0,minion)==8&&g.CardCost(1,minion)==5,"Venture Co adds own minion tax");g.Silence(new MatchTarget(0,wraith.Id));Check(g.CardCost(0,minion)==7&&g.CardCost(1,minion)==4,"Removing global tax preserves other modifier");
  g=MatchFixture("WARLOCK");var portal=g.Summon(0,"VAN_EX1_315");Check(g.CardCost(0,minion)==2&&g.CardCost(0,g.Card("VAN_EX1_009"))==1&&g.CardCost(0,g.Card("VAN_CS2_231"))==0,"Portal discounts minions with one-cost floor and preserves native zero");g.Summon(0,"VAN_EX1_315");Check(g.CardCost(0,minion)==1,"Portals stack down to floor");g.ReturnToHand(new MatchTarget(0,portal.Id));Check(g.CardCost(0,minion)==2,"Portal leaving removes own discount");
  foreach(bool reverse in new[]{false,true}){g=MatchFixture("WARLOCK");g.Summon(0,reverse?"VAN_EX1_076":"VAN_EX1_315");g.Summon(0,reverse?"VAN_EX1_315":"VAN_EX1_076");Check(g.CardCost(0,g.Card("VAN_EX1_393"))==0,"Classic Portal floor precedes first-minion discount regardless of placement order");}
  g=MatchFixture();g.Summon(0,"VAN_EX1_076");hand=Inject(g,"CS2_029");g.Play(0,hand,new MatchTarget(1));Check(g.CardCost(0,minion)==3,"Spell does not consume first minion discount");hand=Inject(g,"CS2_182");g.Play(0,hand);Check(g.Players[0].MinionsPlayedThisTurn==1&&g.CardCost(0,minion)==4,"First minion consumes turn discount");g.EndTurn();g.EndTurn();Check(g.CardCost(0,minion)==3,"First minion discount resets next own turn");
  g=MatchFixture();body=g.Summon(0,"VAN_CS2_182");body.DamageTaken=body.MaxHealth;g.Summon(0,"VAN_CS2_222");Check(body.Health<=0,"New aura cannot revive lethal unit pending cleanup");g.Cleanup();Check(!g.Players[0].Board.Contains(body),"Lethal recipient still removed");
  g=MatchFixture("MAGE");g.Summon(0,"VAN_CS2_222");g.Summon(0,"VAN_EX1_608");body=g.Summon(0,"VAN_CS2_182");Inject(g,"CS2_029");var remote=LanProtocol.ReadView(catalog,LanProtocol.Copy(LanProtocol.View(g,0,"aura",1)));Check(remote.Players[0].Board.Last().MaxHealth==6&&remote.AttackValue(remote.Players[0].Board.Last())==5&&remote.CardCost(0,fire)==3,"Public snapshots agree on aura health attack and cost");match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();inspectMatch=false;ApplyMode(false);RenderMatch();ShowPage("match");Render(Path.Combine(folder,"68-aura-normal.png"));ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"69-aura-minimal.png"));CheckNormalWeights(livePanel);JsonData.Write(Path.Combine(folder,"aura-verification.json"),new{Assertions=checks-before,Cards=AuraRules.Ids,HealthClamp=true,AdjacentPosition=true,FrozenMurlocsBothSides=true,Charge=true,EffectiveCost=true,MaskedSnapshot=true});
 }
}
}
