using System;
using System.IO;
using System.Linq;
namespace Touchfish {
public partial class PanelWindow {
 public void PreviewGraveyardScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);int before=checks;var g=MatchFixture();int spell=Inject(g,"CS2_029");Check(!g.Play(0,spell).Success&&g.Graveyard.Count==0,"Rejected spell does not enter graveyard");g.Play(0,spell,new MatchTarget(1));Check(g.GraveyardFor(0,GraveyardReason.SpellCast,"SPELL").Single().InstanceId==spell&&g.GraveyardFor(1).Length==0,"Cast spell recorded for caster with instance identity");
  var first=g.Summon(0,"VAN_EX1_556");var second=g.Summon(1,"VAN_CS2_231");first.DamageTaken=first.MaxHealth;second.DamageTaken=second.MaxHealth;g.Cleanup();var dead=g.Graveyard.Where(e=>e.Reason==GraveyardReason.MinionDied).ToArray();Check(dead.Length==2&&dead[0].InstanceId==first.Id&&dead[1].InstanceId==second.Id,"Deaths preserve entry order and record both sides");Check(g.Players[0].Board.Single().CardId=="VAN_skele21"&&!g.Graveyard.Any(e=>e.CardId=="VAN_skele21"),"Death recorded before deathrattle and live token not recorded");int count=g.Graveyard.Count;g.Cleanup();Check(g.Graveyard.Count==count,"Repeated cleanup never duplicates death");var token=g.Players[0].Board.Single();token.DamageTaken=token.MaxHealth;g.Cleanup();Check(g.Graveyard.Any(e=>e.CardId=="VAN_skele21"&&e.Reason==GraveyardReason.MinionDied),"Summoned token death is included");
  g=MatchFixture();var unit=g.Summon(0,"VAN_CS2_182");g.ReturnToHand(new MatchTarget(0,unit.Id));Check(g.Graveyard.Count==0,"Normal bounce is not death");unit=g.Summon(0,"VAN_CS2_182");g.Transform(new MatchTarget(0,unit.Id),"VAN_CS2_tk1");Check(g.Graveyard.Count==0,"Transform does not count replaced form as dead");unit=g.Players[0].Board.Single();unit.DamageTaken=unit.MaxHealth;g.Cleanup();Check(g.Graveyard.Single().CardId=="VAN_CS2_tk1","Transformed unit records actual form on death");
  g=MatchFixture("WARLOCK");int discard=Inject(g,"CS2_182");g.DiscardAll(0);Check(g.GraveyardFor(0,GraveyardReason.Discarded).Single().InstanceId==discard&&g.GraveyardFor(0,GraveyardReason.MinionDied).Length==0,"Discarded minion stays distinct from resurrection death pool");for(int n=0;n<10;n++)Inject(g,"CS2_231");g.Players[0].Deck.Clear();g.Players[0].Deck.Add("VAN_CS2_029");g.Draw(0,1);Check(g.GraveyardFor(0,GraveyardReason.Burned,"SPELL").Length==1,"Overdrawn spell recorded separately");unit=g.Summon(0,"VAN_CS2_182");g.ReturnToHand(new MatchTarget(0,unit.Id));Check(g.GraveyardFor(0,GraveyardReason.ReturnOverflow).Length==1&&g.GraveyardFor(0,GraveyardReason.MinionDied).Length==0,"Full-hand bounce is not resurrectable death");
  g=MatchFixture("ROGUE");g.EquipRaw(0,"GAME_DAGGER",1,2,false);int weapon=g.Players[0].WeaponInstanceId;g.EquipRaw(0,"GAME_DAGGER",1,2,false);Check(g.GraveyardFor(0,GraveyardReason.WeaponReplaced).Single().InstanceId==weapon,"Weapon replacement records old instance");g.BreakWeapon(0);g.BreakWeapon(0);Check(g.GraveyardFor(0,GraveyardReason.WeaponDestroyed).Length==1,"Weapon removal recorded once");
  g=MatchFixture("PRIEST");unit=g.Summon(1,"VAN_CS2_182");g.TakeTemporaryControl(0,new MatchTarget(1,unit.Id));unit.DamageTaken=unit.MaxHealth;g.Cleanup();var stolen=g.Graveyard.Single();Check(stolen.Seat==0&&stolen.OriginalOwner==1,"Death records current controller and original owner separately");
  g=MatchFixture("ROGUE");g.Play(0,Inject(g,"GAME_COIN"));g.Play(0,Inject(g,"EX1_137"));g.EndTurn();g.EndTurn();int crack=g.Players[0].Hand.Single(h=>h.CardId=="VAN_EX1_137").Id;g.Play(0,crack);Check(g.GraveyardFor(0,GraveyardReason.SpellCast).Count(e=>e.CardId=="VAN_EX1_137")==2,"Repeated spell use creates independent cast history");
  var masked=LanProtocol.View(g,1,"graveyard",0);string payload=JsonData.Serializer().Serialize(masked);Check(!payload.Contains("Graveyard")&&!payload.Contains("graveyard\":"),"LAN view does not expose authoritative graveyard");var client=LanProtocol.ReadView(catalog,LanProtocol.Copy(masked));Check(client.Graveyard.Count==0&&g.Graveyard.Count>0,"Masked client has no hidden graveyard copy");Check(new MatchEngine(catalog).Graveyard.Count==0,"New match does not share previous graveyard");
  Check(g.Graveyard.Select(e=>e.Sequence).SequenceEqual(Enumerable.Range(1,g.Graveyard.Count)),"History sequence monotonic");
  LeaveLan();match=g;matchViewSeat=0;awaitHandoff=false;ClearPending();ApplyTheme(true,true);ApplyMode(false);ShowPage("match");RenderMatch();Render(Path.Combine(folder,"119-graveyard-no-ui.png"));Check(Width==548&&Height==474,"Backend graveyard adds no enlarged interface");
  File.WriteAllText(Path.Combine(folder,"graveyard-verification.txt"),"PASS: "+(checks-before)+" focused graveyard assertions; spells, deaths, tokens, ordering, controller, discard/burn, weapons, bounce/transform, replay, match isolation and masked serialization. Actual WPF preview; no two-computer test.");
 }
}
}
