using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;

namespace Touchfish {
public partial class PanelWindow {
 int testHandId=50000;
 MatchEngine MatchFixture(string first="MAGE",string second="WARRIOR"){var engine=new MatchEngine(catalog,matchRules.TrainingDeck(first),matchRules.TrainingDeck(second),42);engine.MarkMulliganCompleteForTests();foreach(var p in engine.Players){p.Hand.Clear();p.Mana=p.MaxMana=10;p.Board.Clear();}return engine;}
 int Inject(MatchEngine engine,string baseId,int seat=0){var hand=new HandCard{Id=testHandId++,CardId=baseId=="GAME_COIN"?baseId:"VAN_"+baseId};engine.Players[seat].Hand.Add(hand);return hand.Id;}
 void VerifyMatch(string folder){
  int before=checks;foreach(var cls in Classes){var document=matchRules.TrainingDeck(cls.Key);Check(document.Count==30&&document.Cards.All(p=>matchRules.Supports(catalog.Card(p.Key))),"Nine supported practice decks");}
  var prPlacement=MatchFixture();var prLeft=prPlacement.Summon(0,"VAN_CS2_182");var prRight=prPlacement.Summon(0,"VAN_CS2_179");int prCard=Inject(prPlacement,"EX1_506");prPlacement.Play(0,prCard,null,1);var prOrder=prPlacement.Players[0].Board.Select(u=>u.CardId).ToArray();JsonData.Write(Path.Combine(folder,"summon-position-verification.json"),new{Actual=prOrder,Expected=new[]{prLeft.CardId,"VAN_EX1_506","VAN_EX1_506a",prRight.CardId}});Check(prOrder.SequenceEqual(new[]{prLeft.CardId,"VAN_EX1_506","VAN_EX1_506a",prRight.CardId}),"Battlecry token appears beside source at middle position");
  VerifyMalygos();VerifyEnrage(folder);VerifyAuras(folder);VerifyGiants(folder);VerifyOnyxia(folder);VerifyChoices(folder);VerifyTurnEnd(folder);VerifyDiscard(folder);VerifyClassRestrictions(folder);VerifyHoggerAndHarrison();VerifyPaladinCards();VerifyLegacyLegendaries();Verify040Integration(folder);
  Check(matchRules.RegisteredIds.All(id=>id=="GAME_COIN"||DruidSpellRules.RuntimeCardIds.Contains(id)||catalog.Cards.Values.Any(c=>c.BaseId==id)),"Explicit rules reference real source card IDs");
  var game=new MatchEngine(catalog,matchRules.TrainingDeck("MAGE"),matchRules.TrainingDeck("WARRIOR"),19);game.Mulligan(0,new int[0]);game.Mulligan(1,new int[0]);Check(game.Players[0].Hand.Count==4&&game.Players[1].Hand.Count==5&&game.Players[1].Hand.Any(h=>h.CardId=="GAME_COIN"),"Opening hands and coin");Check(game.Players[0].Mana==1&&game.Players[1].Mana==0,"First-turn mana");Check(game.VisualEvents.Count(e=>e.Kind=="emote")==2&&game.VisualEvents.Where(e=>e.Kind=="emote").Select(e=>e.CardName).SequenceEqual(new[]{HeroEmotes.Opening("MAGE"),HeroEmotes.Opening("WARRIOR")}),"Both heroes automatically announce their opening lines after mulligan");
  game=MatchFixture();var attacker=game.Summon(0,"VAN_CS2_182");var defender=game.Summon(1,"VAN_CS2_179");Check(!game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success&&attacker.AttacksUsed==0,"Summoning sickness");attacker.SummonTurn=0;Check(!game.Attack(0,attacker.Id,new MatchTarget(1)).Success&&attacker.AttacksUsed==0,"Taunt blocks face without consuming attack");Check(game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success&&attacker.Health==2&&defender.Health==1,"Simultaneous combat damage");Check(!game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success,"One attack per turn");
  game=MatchFixture();attacker=game.Summon(0,"VAN_EX1_033");attacker.SummonTurn=0;Check(attacker.Windfury,"Windfury metadata");Check(game.Attack(0,attacker.Id,new MatchTarget(1)).Success&&game.Attack(0,attacker.Id,new MatchTarget(1)).Success&&!game.Attack(0,attacker.Id,new MatchTarget(1)).Success,"Windfury exactly twice");
  game=MatchFixture();attacker=game.Summon(0,"VAN_EX1_170");attacker.SummonTurn=0;defender=game.Summon(1,"VAN_EX1_008");Check(game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success&&!defender.Shield&&defender.Health==1,"Shield blocks poison");attacker.AttacksUsed=0;defender=game.Summon(1,"VAN_CS2_182");Check(game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success&&!game.Players[1].Board.Contains(defender),"Poison destroys surviving target");
  game=MatchFixture();attacker=game.Summon(0,"VAN_CS2_231");attacker.SummonTurn=0;attacker.Stealth=true;defender=game.Summon(1,"VAN_CS2_231");defender.Stealth=true;Check(!game.Attack(0,attacker.Id,new MatchTarget(1,defender.Id)).Success,"Enemy stealth cannot be targeted");Check(game.Attack(0,attacker.Id,new MatchTarget(1)).Success&&!attacker.Stealth,"Attacking removes own stealth");
  game=MatchFixture();defender=game.Summon(1,"VAN_CS2_179");int card=Inject(game,"CS2_029");int mana=game.Players[0].Mana;Check(game.Play(0,card,new MatchTarget(1)).Success&&game.Players[1].Health==24&&game.Players[0].Mana==mana-4,"Targeted spell bypasses taunt");
  game=MatchFixture();card=Inject(game,"CS2_029");game.Players[0].Mana=3;Check(!game.Play(0,card,new MatchTarget(1)).Success&&game.Players[0].Hand.Count==1&&game.Players[0].Mana==3,"Insufficient mana is atomic");game.Players[0].Mana=10;Check(!game.Play(0,card,null).Success&&game.Players[0].Mana==10&&game.Players[0].Hand.Count==1,"Invalid spell target is atomic");
  game=MatchFixture();attacker=game.Summon(0,"VAN_CS2_182");attacker.SummonTurn=0;card=Inject(game,"CS2_024");Check(game.Play(0,card,new MatchTarget(0,attacker.Id)).Success&&attacker.Frozen,"Frostbolt freezes");Check(!game.Attack(0,attacker.Id,new MatchTarget(1)).Success,"Frozen unit cannot attack");game.EndTurn();Check(!attacker.Frozen,"Unused friendly frozen unit thaws at own end");
  game=MatchFixture();defender=game.Summon(1,"VAN_CS2_182");defender.SummonTurn=0;card=Inject(game,"CS2_024");game.Play(0,card,new MatchTarget(1,defender.Id));game.EndTurn();Check(defender.Frozen&&!game.Attack(1,defender.Id,new MatchTarget(0)).Success,"Freeze skips next enemy attack turn");game.EndTurn();Check(!defender.Frozen,"Enemy freeze expires after skipped turn");
  game=MatchFixture("SHAMAN");card=Inject(game,"EX1_238");Check(game.Play(0,card,new MatchTarget(1)).Success&&game.Players[0].Overload==1,"Overload queued");game.EndTurn();game.EndTurn();Check(game.Players[0].LockedMana==1&&game.Players[0].Mana==9,"Overload locks next own turn mana");
  game=MatchFixture("WARRIOR");card=Inject(game,"CS2_106");Check(game.Play(0,card).Success&&game.HeroAttack(0)==3,"Weapon equip");defender=game.Summon(1,"VAN_CS2_231");var weaponHit=game.Attack(0,0,new MatchTarget(1,defender.Id));Check(weaponHit.Success&&game.Players[0].Health==29&&game.Players[0].WeaponDurability==1,"Hero weapon retaliation and durability: "+weaponHit.Message+" hp="+game.Players[0].Health+" dur="+game.Players[0].WeaponDurability);game.Players[0].HeroAttacks=0;Check(game.Attack(0,0,new MatchTarget(1)).Success&&game.Players[0].WeaponDurability==0&&game.HeroAttack(0)==0,"Weapon breaks at zero durability");
  foreach(var cls in Classes){game=MatchFixture(cls.Key);var target=new MatchTarget(1);if(cls.Key=="PRIEST")game.Players[1].Health=20;Check(game.HeroPower(0,game.PowerNeedsTarget(0)?target:null).Success&&game.Players[0].Mana==8&&game.Players[0].PowerUsed,"Nine hero powers");var player=game.Players[0];switch(cls.Key){case "MAGE":Check(game.Players[1].Health==29,"Mage power damage");break;case "PRIEST":Check(game.Players[1].Health==22,"Priest power healing");break;case "WARRIOR":Check(player.Armor==2,"Warrior power armor");break;case "HUNTER":Check(game.Players[1].Health==28,"Hunter power face damage");break;case "WARLOCK":Check(player.Health==28&&player.Hand.Count==1,"Warlock power draw and health");break;case "ROGUE":Check(player.WeaponAttack==1&&player.WeaponDurability==2,"Rogue power dagger");break;case "PALADIN":Check(player.Board.Count==1&&player.Board[0].BaseAttack==1&&player.Board[0].Health==1,"Paladin power recruit");break;case "DRUID":Check(player.Armor==1&&game.HeroAttack(0)==1,"Druid power attack and armor");break;case "SHAMAN":Check(player.Board.Count==1&&new[]{"VAN_CS2_050","VAN_CS2_051","VAN_CS2_052","VAN_NEW1_009"}.Contains(player.Board[0].CardId),"Shaman power valid totem");break;}Check(!game.HeroPower(0,target).Success&&game.Players[0].Mana==8,"One power per turn");}
  game=MatchFixture();for(int n=0;n<7;n++)game.Summon(0,"VAN_CS2_231");card=Inject(game,"CS2_182");Check(!game.Play(0,card).Success&&game.Players[0].Mana==10&&game.Players[0].Hand.Count==1,"Seven-slot cap before spending");
  game=MatchFixture();for(int n=0;n<10;n++)Inject(game,"CS2_231");int deckSize=game.Players[0].Deck.Count;game.Draw(0,1);Check(game.Players[0].Hand.Count==10&&game.Players[0].Deck.Count==deckSize-1,"Hand overflow burns card");game.Players[0].Deck.Clear();game.Draw(0,2);Check(game.Players[0].Fatigue==2&&game.Players[0].Health==27,"Increasing fatigue damage");
  game=MatchFixture();var golem=game.Summon(0,"VAN_EX1_556");var right=game.Summon(0,"VAN_CS2_182");golem.DamageTaken=golem.MaxHealth;game.Cleanup();Check(game.Players[0].Board.Count==2&&game.Players[0].Board[0].CardId=="VAN_skele21"&&game.Players[0].Board[1].Id==right.Id,"Deathrattle replacement position");
  game=MatchFixture();var hoarder=game.Summon(0,"VAN_EX1_096");hoarder.DamageTaken=hoarder.MaxHealth;game.Cleanup();Check(game.Players[0].Hand.Count==1,"Deathrattle draw");
  game=MatchFixture();card=Inject(game,"EX1_019");Check(game.Play(0,card,null,0).Success&&game.Players[0].Board.Count==1,"Battlecry without eligible targets still summons");
  game=MatchFixture();card=Inject(game,"EX1_506");Check(matchRules.Supports(catalog.Card("VAN_EX1_506")),"Murloc Tidehunter is supported");Check(game.Play(0,card).Success&&game.Players[0].Board.Count==2&&game.Players[0].Board[0].CardId=="VAN_EX1_506"&&game.Players[0].Board[1].CardId=="VAN_EX1_506a"&&game.AttackValue(game.Players[0].Board[1])==1&&game.Players[0].Board[1].Health==1&&game.Players[0].Board[1].Race=="MURLOC","Murloc Tidehunter summons its 1/1 scout");
  game=MatchFixture();game.Players[0].Deck.Clear();game.Players[0].Deck.AddRange(new[]{"VAN_CS2_182","VAN_CS2_179"});game.Players[1].Deck.Clear();game.Players[1].Deck.AddRange(new[]{"VAN_CS2_231","VAN_CS2_182"});card=Inject(game,"EX1_050");Check(matchRules.Supports(catalog.Card("VAN_EX1_050"))&&game.Play(0,card).Success&&game.Players[0].Hand.Count==2&&game.Players[0].Hand[0].CardId=="VAN_CS2_182"&&game.Players[0].Hand[1].CardId=="VAN_CS2_179"&&game.Players[1].Hand.Count==2&&game.Players[1].Hand[0].CardId=="VAN_CS2_231"&&game.Players[1].Hand[1].CardId=="VAN_CS2_182","Coldlight Oracle makes both players draw two cards");
  game=MatchFixture();var tidecaller=game.Summon(0,"VAN_EX1_509");var enemyTidecaller=game.Summon(1,"VAN_EX1_509");Check(game.AttackValue(tidecaller)==2&&game.AttackValue(enemyTidecaller)==1,"Murloc Tidecaller does not trigger on its own summon");game.Summon(1,"VAN_EX1_506a");Check(game.AttackValue(tidecaller)==3&&game.AttackValue(enemyTidecaller)==2,"Murloc Tidecaller gains attack when either player summons a Murloc");game.Silence(new MatchTarget(1,enemyTidecaller.Id));game.Summon(0,"VAN_EX1_506a");Check(game.AttackValue(tidecaller)==4&&game.AttackValue(enemyTidecaller)==1,"Silenced Murloc Tidecaller stops triggering and does not lose prior buffs");Check(new[]{"EX1_050","EX1_062","EX1_103","EX1_509"}.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"All four newly implemented Murlocs are playable");
  game=MatchFixture();card=Inject(game,"CS2_196");Check(game.Play(0,card).Success&&game.Players[0].Board.Count==2&&game.Players[0].Board[1].CardId=="VAN_CS2_boar"&&game.AttackValue(game.Players[0].Board[1])==1&&game.Players[0].Board[1].Health==1,"Razorfen Hunter summons its 1/1 boar");
  game=MatchFixture();card=Inject(game,"CS2_151");Check(game.Play(0,card).Success&&game.Players[0].Board.Count==2&&game.Players[0].Board[1].CardId=="VAN_CS2_152"&&game.AttackValue(game.Players[0].Board[1])==2&&game.Players[0].Board[1].Health==2,"Silver Hand Knight summons its 2/2 squire");
  game=MatchFixture();for(int n=0;n<5;n++)game.Summon(0,"VAN_CS2_231");card=Inject(game,"EX1_506");Check(game.Play(0,card).Success&&game.Players[0].Board.Count==7&&game.Players[0].Board.Last().CardId=="VAN_EX1_506a","Battlecry token fills the final board slot");
  game=MatchFixture();for(int n=0;n<6;n++)game.Summon(0,"VAN_CS2_231");card=Inject(game,"EX1_506");Check(game.Play(0,card).Success&&game.Players[0].Board.Count==7&&game.Players[0].Board.Count(m=>m.CardId=="VAN_EX1_506a")==0,"Battlecry resolves without a token when the board is full");
  game=MatchFixture();var dragon=game.Summon(1,"VAN_NEW1_023");card=Inject(game,"CS2_029");Check(!game.Play(0,card,new MatchTarget(1,dragon.Id)).Success,"Faerie Dragon rejects spell");card=Inject(game,"CS2_189");Check(game.Play(0,card,new MatchTarget(1,dragon.Id)).Success,"Battlecry can target spell-protected minion");
  game=MatchFixture();var unit=game.Summon(0,"VAN_CS2_231");game.Buff(new MatchTarget(0,unit.Id),4,4);unit.DamageTaken=4;game.Silence(new MatchTarget(0,unit.Id));game.Cleanup();Check(unit.Health==1&&game.Players[0].Board.Contains(unit),"Silence clamps current health instead of killing wounded buffed unit");
  game=MatchFixture();game.Summon(0,"VAN_EX1_284");card=Inject(game,"CS2_029");Check(game.Play(0,card,new MatchTarget(1)).Success&&game.Players[1].Health==23,"Spell damage bonus");
  game=MatchFixture();game.Players[1].Armor=3;card=Inject(game,"CS2_029");game.Play(0,card,new MatchTarget(1));Check(game.Players[1].Armor==0&&game.Players[1].Health==27,"Armor absorbs damage first");
  game=MatchFixture();card=Inject(game,"GAME_COIN");game.Players[0].Mana=0;game.Play(0,card);Check(game.Players[0].Mana==1&&game.Players[0].MaxMana==10,"Coin gives temporary available mana only");
  game=MatchFixture();var bothA=game.Summon(0,"VAN_CS2_231");var bothB=game.Summon(1,"VAN_CS2_231");bothA.SummonTurn=0;game.Attack(0,bothA.Id,new MatchTarget(1,bothB.Id));Check(game.Players.All(p=>p.Board.Count==0),"Simultaneous lethal trade removes both units");
  game=MatchFixture();unit=game.Summon(0,"VAN_CS2_182");game.Summon(0,"VAN_EX1_162");Check(game.AttackValue(unit)==5,"Adjacent attack aura");
  game=MatchFixture("WARRIOR");defender=game.Summon(1,"VAN_CS2_182");card=Inject(game,"CS2_108");Check(!game.Play(0,card,new MatchTarget(1,defender.Id)).Success&&game.Players[0].Mana==10,"Execute rejects undamaged target");
  game=MatchFixture();game.Players[1].Health=2;card=Inject(game,"CS2_029");Check(game.Play(0,card,new MatchTarget(1)).Success&&game.Winner==0,"Hero lethal ends match");Check(!game.EndTurn().Success,"No actions after victory");
  var bad=matchRules.TrainingDeck("MAGE");var remove=bad.Cards.First();bad.Cards.Remove(remove.Key);bad.Cards["VAN_EX1_287"]=remove.Value;bool rejected=false;try{new MatchEngine(catalog,bad,matchRules.TrainingDeck("WARRIOR"),1);}catch(InvalidOperationException){rejected=true;}Check(rejected,"Unsupported effects rejected at start");
  var coverage=catalog.Deckable(catalog.Pool("classic-2014")).Select(c=>new {Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new {SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Implemented card rules for LAN and local test; partial Classic rules"});
  ApplyTheme(true,true);ApplyMode(true);RefreshLobbyDecks();ShowPage("lobby");Render(Path.Combine(folder,"30-class-selection.png"));
  match=MatchFixture();matchViewSeat=0;awaitHandoff=false;inspectMatch=false;ClearPending();attacker=match.Summon(0,"VAN_CS2_182");attacker.SummonTurn=0;defender=match.Summon(1,"VAN_CS2_179");Inject(match,"CS2_029");Inject(match,"CS2_024");Inject(match,"CS2_182");RenderMatch();ShowPage("match");Render(Path.Combine(folder,"31-live-match.png"));ClickMatchTarget(new MatchTarget(0,attacker.Id));Check(pending=="attack"&&pendingId==attacker.Id,"UI first click selects attacker");Render(Path.Combine(folder,"32-selected-attacker.png"));ClickMatchTarget(new MatchTarget(1,defender.Id));Check(pending==""&&attacker.AttacksUsed==1&&defender.Health==1,"UI second click resolves attack");
  int spell=match.Players[0].Hand.First(h=>h.CardId=="VAN_CS2_029").Id;BeginCard(spell);Check(pending=="play","UI spell selection");ClickMatchTarget(new MatchTarget(1));Check(match.Players[1].Health==24&&pending=="","UI spell target resolves damage");Render(Path.Combine(folder,"33-after-actions.png"));
  int summon=match.Players[0].Hand.First(h=>h.CardId=="VAN_CS2_182").Id;BeginCard(summon);ClickEmptySlot(0,1);Check(match.Players[0].Board.Count==2,"UI hand to empty slot summons");foreach(var border in liveUnits){var bounds=border.TransformToAncestor(livePanel).TransformBounds(new Rect(0,0,border.ActualWidth,border.ActualHeight));Check(bounds.Right<=livePanel.ActualWidth+1&&bounds.Bottom<=livePanel.ActualHeight+1,"Live board fits minimal viewport");}
  match=MatchFixture();matchViewSeat=0;for(int seat=0;seat<2;seat++)for(int n=0;n<7;n++)match.Summon(seat,"VAN_CS2_179");ClearPending();RenderMatch();Render(Path.Combine(folder,"35-live-full-board.png"));Check(liveUnits.Count==14,"Fourteen live units visible");foreach(var border in liveUnits){var bounds=border.TransformToAncestor(livePanel).TransformBounds(new Rect(0,0,border.ActualWidth,border.ActualHeight));Check(bounds.Right<=livePanel.ActualWidth+1&&bounds.Bottom<=livePanel.ActualHeight+1,"Full live board within viewport");}ApplyMode(false);RenderMatch();Render(Path.Combine(folder,"36-live-normal.png"));ApplyMode(true);
  awaitHandoff=true;match.EndTurn();RenderMatch();Render(Path.Combine(folder,"34-turn-handoff.png"));awaitHandoff=false;matchViewSeat=match.Active;RenderMatch();Check(matchViewSeat==1&&match.Active==1,"Hotseat view switches player");CheckNormalWeights(livePanel);
  match.Players[matchViewSeat].Hand.Clear();for(int n=0;n<10;n++)Inject(match,n%2==0?"CS2_029":"CS2_024",matchViewSeat);RenderMatch();UpdateLayout();Check(liveHandScroll.ScrollableWidth>0,"Ten-card hand has horizontal scrolling");liveHandScroll.ScrollToHorizontalOffset(liveHandScroll.ScrollableWidth);UpdateLayout();Check(liveHandScroll.HorizontalOffset>0,"Last hand cards accessible by horizontal scroll");Render(Path.Combine(folder,"37-ten-card-hand.png"));
  VerifyPlacement(folder);
  var simulations=new List<object>();foreach(var cls in Classes){var simulated=new MatchEngine(catalog,matchRules.TrainingDeck(cls.Key),matchRules.TrainingDeck("WARRIOR"),73);simulated.Mulligan(0,new int[0]);simulated.Mulligan(1,new int[0]);int actions=0;for(int turn=0;turn<240&&!simulated.Finished;turn++){
   int seat=simulated.Active;foreach(var hand in simulated.Players[seat].Hand.ToArray()){if(simulated.Finished)break;var definition=simulated.Card(hand.CardId);string mask=simulated.Rules.Target(definition,null,ComboRules.Active(simulated));var target=mask=="NONE"?null:FirstTestTarget(simulated,seat,mask,definition.Type=="SPELL");var result=simulated.Play(seat,hand.Id,target);if(result.Success)actions++;}
   if(!simulated.Finished){var target=simulated.PowerNeedsTarget(seat)?new MatchTarget(simulated.Players[seat].ClassId=="PRIEST"?seat:1-seat):null;if(simulated.HeroPower(seat,target).Success)actions++;}
   foreach(var actor in simulated.Players[seat].Board.ToArray())for(int attack=0;attack<2&&!simulated.Finished;attack++){var taunt=simulated.Players[1-seat].Board.FirstOrDefault(m=>m.Taunt&&!m.Stealth);var target=new MatchTarget(1-seat,taunt==null?0:taunt.Id);if(!simulated.Attack(seat,actor.Id,target).Success)break;actions++;}
   if(!simulated.Finished){var taunt=simulated.Players[1-seat].Board.FirstOrDefault(m=>m.Taunt&&!m.Stealth);if(simulated.Attack(seat,0,new MatchTarget(1-seat,taunt==null?0:taunt.Id)).Success)actions++;}
   Check(simulated.Players.All(p=>p.Board.Count<=7&&p.Hand.Count<=10&&p.Mana>=0&&p.Mana<=10&&p.Board.All(m=>m.Health>0)),"Simulation state invariants");if(!simulated.Finished)simulated.EndTurn();
  }Check(simulated.Finished,"Nine classes can complete a match");simulations.Add(new {ClassId=cls.Key,Turns=simulated.Turn,Winner=simulated.Winner,Actions=actions});}JsonData.Write(Path.Combine(folder,"match-simulations.json"),simulations);
  JsonData.Write(Path.Combine(folder,"match-verification.json"),new {Assertions=checks-before,SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,LocalTest=true,LanSupported=true,ClickAttack=true,ClickSpells=true,OptionalMinionPlacement=true,HeroPowers=9,FullClassicRules=false});
 }
 void VerifyPlacement(string folder){
  match=MatchFixture();matchViewSeat=0;awaitHandoff=false;choosePosition=false;inspectMatch=false;ClearPending();matchHandScroll=0;
  var a=match.Summon(0,"VAN_CS2_231");var b=match.Summon(0,"VAN_CS2_182");var c=match.Summon(0,"VAN_CS2_179");var enemy=match.Summon(1,"VAN_CS2_182");int hand=Inject(match,"EX1_170");BeginCard(hand);Check(placementButtons.Count==0,"Placement controls hidden by default");TogglePlacement();Check(placementButtons.Count==6,"Only own occupied units offer left and right");Check(match.Players[0].Hand.Count==1&&match.Players[0].Mana==10,"Position selection does not spend resources");
  Render(Path.Combine(folder,"38-choose-position.png"));CheckNormalWeights(livePanel);placementButtons[2].RaiseEvent(new RoutedEventArgs(Button.ClickEvent));var board=match.Players[0].Board;Check(board.Count==4&&board[0].Id==a.Id&&board[1].CardId=="VAN_EX1_170"&&board[2].Id==b.Id&&board[3].Id==c.Id,"ABC with D left of B becomes ADBC");Check(pending==""&&placementButtons.Count==0,"Placement controls disappear after summon");
  hand=Inject(match,"CS2_231");BeginCard(hand);ClickRelativeSlot(0,b.Id,true);Check(board[3].CardId=="VAN_CS2_231"&&board[2].Id==b.Id&&board[4].Id==c.Id,"Right placement uses current anchor position");
  hand=Inject(match,"EX1_019");BeginCard(hand);int count=board.Count,mana=match.Players[0].Mana;ClickMatchTarget(new MatchTarget(0,c.Id));Check(board.Count==count&&match.Players[0].Mana==mana&&pendingPosition==-1,"Targeted battlecry waits for position");ClickRelativeSlot(0,b.Id,false);Check(pendingPosition==2&&board.Count==count&&placementButtons.Count==0,"Battlecry position retained while awaiting target");ClickMatchTarget(new MatchTarget(1,enemy.Id));Check(board.Count==count&&match.Players[0].Mana==mana&&pendingPosition==2,"Invalid battlecry target keeps position and resources");int hp=c.Health;ClickMatchTarget(new MatchTarget(0,c.Id));Check(board[2].CardId=="VAN_EX1_019"&&board[3].Id==b.Id&&c.Health==hp+1,"Battlecry resolves at selected position and buffs chosen target");
  hand=Inject(match,"CS2_231");BeginCard(hand);InspectMatchCard(match.Card("VAN_CS2_182"));Check(board.Count==6&&pending=="play","Inspecting details does not summon");inspectMatch=false;RenderMatch();ApplyMode(false);RenderMatch();Render(Path.Combine(folder,"39-position-normal.png"));ApplyMode(true);RenderMatch();Render(Path.Combine(folder,"40-position-minimal-six.png"));ApplyTheme(false,false);RenderMatch();Render(Path.Combine(folder,"41-position-wps.png"));ApplyTheme(true,true);RenderMatch();UpdateLayout();foreach(var border in liveUnits){var bounds=border.TransformToAncestor(livePanel).TransformBounds(new Rect(0,0,border.ActualWidth,border.ActualHeight));Check(bounds.Right<=livePanel.ActualWidth+1&&bounds.Bottom<=livePanel.ActualHeight+1,"Placement controls preserve compact board bounds");}ClickRelativeSlot(1,enemy.Id,false);ClickRelativeSlot(0,-999,false);Check(board.Count==6&&pending=="play","Enemy and stale anchors cannot place minions");ClickRelativeSlot(0,a.Id,false);Check(board.Count==7&&board[0].CardId=="VAN_CS2_231"&&board[1].Id==a.Id,"Front placement reaches seven slots");hand=Inject(match,"CS2_231");BeginCard(hand);Check(pending==""&&placementButtons.Count==0&&match.Players[0].Hand.Any(h=>h.Id==hand),"Full board rejects placement before spending");
  match=MatchFixture();a=match.Summon(0,"VAN_CS2_182");a.SummonTurn=0;ClearPending();hand=Inject(match,"CS2_029");BeginCard(hand);Check(placementButtons.Count==0,"Spells have no position controls");ClickMatchTarget(new MatchTarget(1));Check(match.Players[1].Health==24,"Position mode preserves spell targeting");ClickMatchTarget(new MatchTarget(0,a.Id));Check(pending=="attack"&&placementButtons.Count==0,"Position mode preserves attack selection");ClearPending();hand=Inject(match,"CS2_231");BeginCard(hand);TogglePlacement();Check(placementButtons.Count==0&&pending=="play","Closing position toggle restores ordinary placement");ClickEmptySlot(0,1);Check(match.Players[0].Board.Count==2,"Default placement still appends at empty slot");
  choosePosition=true;match=MatchFixture();ClearPending();hand=Inject(match,"EX1_019");BeginCard(hand);ClickEmptySlot(0,0);Check(match.Players[0].Board.Count==1&&pending=="","Empty board permits targeted battlecry with no eligible target");choosePosition=false;RenderMatch();
 }
 void VerifyHoggerAndHarrison(){
  var game=MatchFixture();var hogger=game.Summon(0,"VAN_NEW1_040");Check(matchRules.Supports(catalog.Card("VAN_NEW1_040")),"Hogger is supported");game.EndTurn();Check(game.Players[0].Board.Count==2&&game.Players[0].Board[1].CardId=="GAME_GNOLL"&&game.Players[0].Board[1].Health==2&&game.Players[0].Board[1].Taunt,"Hogger summons a 2/2 Taunt Gnoll at its controller's turn end");
  game=MatchFixture();hogger=game.Summon(0,"VAN_NEW1_040");hogger.Silenced=true;game.EndTurn();Check(game.Players[0].Board.Count==1,"Silenced Hogger does not summon a Gnoll");
  game=MatchFixture();hogger=game.Summon(0,"VAN_NEW1_040");for(int n=0;n<6;n++)game.Summon(0,"VAN_CS2_231");game.EndTurn();Check(game.Players[0].Board.Count==7&&game.Players[0].Board.All(u=>u.CardId!="GAME_GNOLL"),"Hogger respects the seven-minion board limit");
  game=MatchFixture();var opponentHogger=game.Summon(1,"VAN_NEW1_040");game.EndTurn();Check(game.Players[1].Board.Count==1,"Hogger only triggers at its controller's turn end");game.EndTurn();Check(game.Players[1].Board.Count==2&&game.Players[1].Board[1].CardId=="GAME_GNOLL","Opponent Hogger triggers at its own turn end");
  game=MatchFixture();int harrison=Inject(game,"EX1_558");game.Players[1].WeaponId="VAN_CS2_106";game.Players[1].WeaponAttack=3;game.Players[1].WeaponDurability=2;game.Players[0].Deck.Clear();game.Players[0].Deck.AddRange(new[]{"VAN_CS2_182","VAN_CS2_179"});Check(matchRules.Supports(catalog.Card("VAN_EX1_558"))&&game.Play(0,harrison).Success,"Harrison Jones is supported and can be played");Check(game.Players[1].WeaponId==null&&game.Players[1].WeaponDurability==0&&game.Players[0].Hand.Select(h=>h.CardId).SequenceEqual(new[]{"VAN_CS2_182","VAN_CS2_179"}),"Harrison destroys the enemy weapon and draws its remaining durability");
  game=MatchFixture();harrison=Inject(game,"EX1_558");Check(game.Play(0,harrison).Success&&game.Players[0].Hand.Count==0&&game.Players[0].Board.Any(u=>u.CardId=="VAN_EX1_558"),"Harrison still summons without an enemy weapon and draws zero cards");
 }
 void VerifyPaladinCards(){
  string[] ids={"EX1_349","EX1_362","EX1_363","EX1_365","EX1_382","EX1_383"};Check(ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"Six Paladin cards are enabled");
  var game=MatchFixture("PALADIN");var tirion=game.Summon(0,"VAN_EX1_383");Check(tirion.Taunt&&tirion.Shield&&tirion.BaseAttack==6&&tirion.BaseHealth==6,"Tirion starts as a 6/6 Taunt with Divine Shield");tirion.DamageTaken=tirion.MaxHealth;game.Cleanup();Check(game.Players[0].WeaponId=="GAME_ASHBRINGER"&&game.Players[0].WeaponAttack==5&&game.Players[0].WeaponDurability==3&&game.Card(game.Players[0].WeaponId).Name=="灰烬使者","Tirion equips Ashbringer on death");
  game=MatchFixture("PALADIN");int favor=Inject(game,"EX1_349");game.Players[1].Hand.AddRange(new[]{new HandCard{Id=testHandId++,CardId="VAN_CS2_231"},new HandCard{Id=testHandId++,CardId="VAN_CS2_231"},new HandCard{Id=testHandId++,CardId="VAN_CS2_231"}});game.Players[0].Deck.AddRange(new[]{"VAN_CS2_231","VAN_CS2_231","VAN_CS2_231"});Check(game.Play(0,favor).Success&&game.Players[0].Hand.Count==3,"Divine Favor draws until both players have equal hand sizes");
  game=MatchFixture("PALADIN");var friend=game.Summon(0,"VAN_CS2_182");int protector=Inject(game,"EX1_362");Check(game.Play(0,protector,new MatchTarget(0,friend.Id)).Success&&friend.Shield&&game.Players[0].Board.Count==2,"Argent Protector gives a friendly minion Divine Shield");
  game=MatchFixture("PALADIN");var wrathTarget=game.Summon(1,"VAN_CS2_182");int wrath=Inject(game,"EX1_365");game.Players[0].Deck.Clear();game.Players[0].Deck.Add("VAN_CS2_182");int wrathDamage=catalog.Card("VAN_CS2_182").Cost;Check(game.Play(0,wrath,new MatchTarget(1,wrathTarget.Id)).Success&&wrathTarget.Health==wrathTarget.MaxHealth-wrathDamage&&game.Players[0].Hand.Any(h=>h.CardId=="VAN_CS2_182"),"Holy Wrath draws its top card and damages the chosen minion by that card's cost");
  game=MatchFixture("PALADIN");var blessed=game.Summon(1,"VAN_CS2_182");int wisdom=Inject(game,"EX1_363");game.Players[0].Deck.Clear();game.Players[0].Deck.Add("VAN_CS2_231");Check(game.Play(0,wisdom,new MatchTarget(1,blessed.Id)).Success&&blessed.WisdomBlessings0==1,"Blessing of Wisdom attaches to a minion");blessed.SummonTurn=0;game.Turn=2;game.Active=1;Check(game.Attack(1,blessed.Id,new MatchTarget(0)).Success&&game.Players[0].Hand.Any(h=>h.CardId=="VAN_CS2_231"),"Blessing of Wisdom draws for its caster when the enchanted minion attacks");
  game=MatchFixture("PALADIN");var enemy=game.Summon(1,"VAN_CS2_182");int aldor=Inject(game,"EX1_382");Check(game.Play(0,aldor,new MatchTarget(1,enemy.Id)).Success&&game.AttackValue(enemy)==1&&game.Players[0].Board.Any(u=>u.CardId=="VAN_EX1_382"),"Aldor Peacekeeper sets an enemy minion's attack to 1");
 }
 void VerifyLegacyLegendaries(){
  var uther=HeroEmotes.Options("PALADIN");Check(uther.Length==6&&uther[0].Key=="感谢"&&uther[1].Key=="问候"&&uther[2].Key=="称赞"&&uther[3].Key=="惊叹"&&uther[4].Key=="失误"&&uther[5].Key=="威胁"&&uther[0].Value=="谢谢你"&&uther[1].Value=="很高兴见到你"&&uther[2].Value=="打得不错"&&HeroEmotes.Opening("PALADIN")=="荣耀将赐予我力量"&&HeroEmotes.Defeat("PALADIN")=="胜利属于你"&&Classes.All(c=>HeroEmotes.Options(c.Key).Length==6&&!String.IsNullOrEmpty(HeroEmotes.Name(c.Key))),"All classic heroes have the six requested manual emotes plus automatic opening and defeat lines");
  var lost=MatchFixture();lost.Players[0].Health=1;lost.Damage(new MatchTarget(0),1);lost.Cleanup();Check(lost.Winner==1&&lost.VisualEvents.Count(e=>e.Kind=="emote")==1&&lost.VisualEvents.Last(e=>e.Kind=="emote").Seat==0&&lost.VisualEvents.Last(e=>e.Kind=="emote").CardName==HeroEmotes.Defeat("MAGE"),"Losing hero automatically shows its defeat line exactly once");lost.Cleanup();Check(lost.VisualEvents.Count(e=>e.Kind=="emote")==1,"Repeated cleanup never replays the defeat line");
  string[] ids={"EX1_110","EX1_116","EX1_016"};Check(ids.All(id=>matchRules.Supports(catalog.Card("VAN_"+id))),"Cairne, Leeroy and Sylvanas are enabled");
  var game=MatchFixture();var cairne=game.Summon(0,"VAN_EX1_110");cairne.DamageTaken=cairne.MaxHealth;game.Cleanup();Check(game.Players[0].Board.Count==1&&game.Players[0].Board[0].CardId=="VAN_EX1_110t"&&game.Players[0].Board[0].BaseAttack==4&&game.Players[0].Board[0].Health==5,"Cairne summons 4/5 Baine on death");
  game=MatchFixture();int leeroy=Inject(game,"EX1_116");Check(game.Play(0,leeroy).Success&&game.Players[0].Board.Single().Charge&&game.Players[1].Board.Count==2&&game.Players[1].Board.All(u=>u.BaseAttack==1&&u.Health==1),"Leeroy charges and gives opponent two 1/1 Whelps");
  game=MatchFixture();var enemy=game.Summon(1,"VAN_CS2_182");var sylvanas=game.Summon(0,"VAN_EX1_016");sylvanas.DamageTaken=sylvanas.MaxHealth;game.Cleanup();Check(game.Players[1].Board.Count==0&&game.Players[0].Board.Any(u=>u.Id==enemy.Id&&u.Owner==0),"Sylvanas steals a random enemy minion on death");
 }
 void VerifyMalygos(){
  Check(catalog.Card("VAN_EX1_563").SpellDamage==5,"Malygos imports printed +5 magnitude instead of raw presence marker");
  var game=MatchFixture();var malygos=game.Summon(0,"VAN_EX1_563");int fire=Inject(game,"CS2_029");Check(game.SpellPower(0)==5&&game.Play(0,fire,new MatchTarget(1)).Success&&game.Players[1].Health==19,"Malygos makes Fireball deal eleven");
  game=MatchFixture();malygos=game.Summon(0,"VAN_EX1_563");int frost=Inject(game,"CS2_024");Check(game.Play(0,frost,new MatchTarget(1)).Success&&game.Players[1].Health==22&&game.Players[1].Frozen,"Malygos makes Frostbolt deal eight and freeze");
  game=MatchFixture();game.Summon(0,"VAN_EX1_563");int missiles=Inject(game,"EX1_277");Check(game.Play(0,missiles).Success&&game.Players[1].Health==22,"Malygos gives Arcane Missiles eight one-damage hits");
  game=MatchFixture();malygos=game.Summon(0,"VAN_EX1_563");game.Summon(0,"VAN_EX1_284");Check(game.SpellPower(0)==6,"Malygos stacks with another spell-power minion");game.Silence(new MatchTarget(0,malygos.Id));fire=Inject(game,"CS2_029");Check(game.SpellPower(0)==1&&game.Play(0,fire,new MatchTarget(1)).Success&&game.Players[1].Health==23,"Silence removes only Malygos bonus");
  game=MatchFixture();malygos=game.Summon(0,"VAN_EX1_563");malygos.DamageTaken=malygos.MaxHealth;game.Cleanup();fire=Inject(game,"CS2_029");Check(game.SpellPower(0)==0&&game.Play(0,fire,new MatchTarget(1)).Success&&game.Players[1].Health==24,"Malygos death removes bonus");
  game=MatchFixture();game.Summon(1,"VAN_EX1_563");fire=Inject(game,"CS2_029");Check(game.Play(0,fire,new MatchTarget(1)).Success&&game.Players[1].Health==24,"Enemy Malygos never buffs own spell");
  game=MatchFixture();game.Summon(0,"VAN_EX1_563");Check(game.HeroPower(0,new MatchTarget(1)).Success&&game.Players[1].Health==29,"Malygos does not buff hero power");int archer=Inject(game,"CS2_189");Check(game.Play(0,archer,new MatchTarget(1)).Success&&game.Players[1].Health==28,"Malygos does not buff battlecry damage");
 }
 MatchTarget FirstTestTarget(MatchEngine game,int seat,string mask,bool ability){foreach(var target in game.Characters(1-seat).Reverse().Concat(game.Characters(seat)))try{game.ValidateTarget(seat,target,mask,ability);return target;}catch(InvalidOperationException){}return null;}
}
}
