using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Documents;

namespace Touchfish {
public partial class PanelWindow {
 MatchEngine match;MatchRules matchRules;Grid lobbyPanel,livePanel;ComboBox myClass,opponentClass,myDeck,opponentDeck;TextBlock lobbyNotice,livePrompt,enemyHandStatus;
 string pending="",pendingChoice;int pendingId,pendingPosition=-1,matchViewSeat,handoffSeat;bool inspectMatch,awaitHandoff,testTakeOpen,emoteOpen;CardRecord inspectedCard;int inspectedUnitId;readonly HashSet<int> selectedMulligan=new HashSet<int>();
 string matchUiSession;
 List<Border> liveUnits=new List<Border>();
 Dictionary<int,FrameworkElement> handCardVisuals=new Dictionary<int,FrameworkElement>();TextBlock deckCountText;
 double matchHandScroll;ScrollViewer liveHandScroll;bool choosePosition;List<Button> placementButtons=new List<Button>();
 void BuildMatchUi(){
  lobbyPanel=new Grid{Margin=new Thickness(12,8,12,8),Visibility=Visibility.Collapsed};foreach(var height in new double[]{24,50,50,-1,28})lobbyPanel.RowDefinitions.Add(new RowDefinition{Height=height<0?new GridLength(1,GridUnitType.Star):new GridLength(height)});Put(shell,lobbyPanel,4);lobbyPanel.Children.Add(T("test · 本地自对战",12,Ink));
  var players=new Grid();players.ColumnDefinitions.Add(new ColumnDefinition());players.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(8)});players.ColumnDefinitions.Add(new ColumnDefinition());
  myClass=Picker(Classes);opponentClass=Picker(Classes);myClass.SelectedItem=Classes.First(c=>c.Key==draft.ClassId);opponentClass.SelectedItem=Classes.First(c=>c.Key=="WARRIOR");players.Children.Add(LobbyField("玩家 1",myClass));var second=LobbyField("玩家 2",opponentClass);Grid.SetColumn(second,2);players.Children.Add(second);Put(lobbyPanel,players,1);
  var decks=new Grid();decks.ColumnDefinitions.Add(new ColumnDefinition());decks.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(8)});decks.ColumnDefinitions.Add(new ColumnDefinition());myDeck=Picker(new Choice[0]);opponentDeck=Picker(new Choice[0]);decks.Children.Add(LobbyField("卡组",myDeck));var other=LobbyField("卡组",opponentDeck);Grid.SetColumn(other,2);decks.Children.Add(other);Put(lobbyPanel,decks,2);BindDeckClass(myClass,myDeck);BindDeckClass(opponentClass,opponentDeck);RefreshLobbyDecks();
  lobbyNotice=T("本地双人轮流操作。可使用已实现效果的卡组，或直接选择基础练习卡组。无需满 30 张；双方开局 10 个满水晶，可从剩余牌库指定取牌。仅用于 test。",10,Muted);lobbyNotice.TextWrapping=TextWrapping.Wrap;Put(lobbyPanel,lobbyNotice,3);
  var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};var resume=Btn("返回对局",70);resume.Click+=(s,e)=>{if(match!=null){RenderMatch();ShowPage("match");}else lobbyNotice.Text="尚未开始对局。";};buttons.Children.Add(resume);var start=Btn("开始对局",70);start.Foreground=Ink;start.Click+=(s,e)=>StartConfiguredMatch();buttons.Children.Add(start);Put(lobbyPanel,buttons,4);
  livePanel=new Grid{Margin=new Thickness(4,2,4,2),Visibility=Visibility.Collapsed};Put(shell,livePanel,4);BuildMatchEffects();
 }
 FrameworkElement LobbyField(string caption,ComboBox picker){var stack=new StackPanel();stack.Children.Add(T(caption,10,Muted));picker.Height=25;picker.Margin=new Thickness(0,4,0,0);stack.Children.Add(picker);return stack;}
 void RefreshLobbyDecks(){if(myDeck==null)return;var choices=new List<Choice>{new Choice("training","基础练习卡组"),new Choice("draft","当前编辑卡组")};choices.AddRange(savedDecks.Select(d=>new Choice(d.Id,d.Name)));myDeck.ItemsSource=choices.ToArray();opponentDeck.ItemsSource=choices.ToArray();myDeck.SelectedIndex=opponentDeck.SelectedIndex=0;}
 void OpenMatch(){OpenLan();}
 DeckDocument LobbyDeck(ComboBox classChoice,ComboBox deckChoice,bool complete=true){string key=((Choice)deckChoice.SelectedItem).Key;SyncChosenDeckClass(classChoice,deckChoice);var document=key=="training"?matchRules.TrainingDeck(((Choice)classChoice.SelectedItem).Key):SelectedBoundDeck(key);DeckRules.Validate(catalog,document,complete);return document;}

 void StartConfiguredMatch(){if(!localTest&&!previewRun)return;try{var first=LobbyDeck(myClass,myDeck,false);var second=LobbyDeck(opponentClass,opponentDeck,false);match=new MatchEngine(catalog,first,second,Environment.TickCount,true);testTakeOpen=false;emoteOpen=false;selectedMulligan.Clear();matchViewSeat=0;matchHandScroll=0;awaitHandoff=false;ClearPending();inspectMatch=false;RenderMatch();ShowPage("match");Record("开始本地双人对局");}catch(Exception ex){if(!(ex is InvalidOperationException||ex is System.IO.InvalidDataException))throw;lobbyNotice.Text=ex.Message;}}
 void ClearPending(){pending="";pendingChoice=null;pendingId=0;pendingPosition=-1;}
 bool NeedsPlacement(){if(!choosePosition||!CanMatchInput()||pending!="play"||pendingPosition>=0)return false;var hand=match.Players[matchViewSeat].Hand.FirstOrDefault(h=>h.Id==pendingId);return hand!=null&&match.Card(hand.CardId).Type=="MINION";}
 void TogglePlacement(){choosePosition=!choosePosition;RenderMatch();status.Text=choosePosition?"位置选择已开启：选随从牌后，点击已有随从的左或右。":"位置选择已关闭。";}
 void ClickRelativeSlot(int seat,int anchorId,bool right){if(!NeedsPlacement()||seat!=matchViewSeat)return;int index=match.Players[seat].Board.FindIndex(u=>u.Id==anchorId);if(index<0){status.Text="该随从已不在战场上，请重新选择位置。";return;}ClickEmptySlot(seat,index+(right?1:0));}
 void RenderMatch(){
  if(match==null||livePanel==null)return;if(minimal)emoteOpen=false;if(!lanMode)match.EntranceAnimationsEnabled=fullEffects&&!minimal;if(matchUiSession!=match.VisualSession){matchUiSession=match.VisualSession;selectedMulligan.Clear();emoteOpen=false;}CaptureMatchVisuals();livePanel.Children.Clear();livePanel.RowDefinitions.Clear();liveUnits.Clear();placementButtons.Clear();foreach(var h in new double[]{18,minimal?24:42,-1,minimal?10:20,-1,minimal?24:42,minimal?36:58})livePanel.RowDefinitions.Add(new RowDefinition{Height=h<0?new GridLength(1,GridUnitType.Star):new GridLength(h)});
  livePanel.RowDefinitions[2].MinHeight=livePanel.RowDefinitions[4].MinHeight=minimal?54:100;
  var heading=new Grid();heading.ColumnDefinitions.Add(new ColumnDefinition());heading.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});livePrompt=T(!match.MulliganComplete?"起手换牌 · 点击牌后确认":match.Finished?(match.Winner==-1?"平局":"玩家 "+(match.Winner+1)+" 获胜"):pending==""?(lanMode?LanTurnHint():"第 "+((match.Turn+1)/2)+" 回合 · 玩家 "+(match.Active+1)):PendingHint(),10,Muted);livePrompt.TextTrimming=TextTrimming.CharacterEllipsis;heading.Children.Add(livePrompt);
  var actions=new StackPanel{Orientation=Orientation.Horizontal};if(localTest&&!lanMode&&match.TestMode){var take=Btn("取",18);take.Height=18;take.FontSize=9;take.Padding=new Thickness(0);take.ToolTip="从己方剩余牌库指定取牌";take.IsEnabled=match.MulliganComplete&&CanMatchInput();take.Click+=(s,e)=>{testTakeOpen=!testTakeOpen;ClearPending();inspectMatch=false;RenderMatch();};actions.Children.Add(take);}var heroAttack=Btn("攻",18);heroAttack.Height=18;heroAttack.FontSize=9;heroAttack.Padding=new Thickness(0);heroAttack.ToolTip="使用英雄攻击";heroAttack.IsEnabled=match.MulliganComplete&&CanMatchInput()&&match.CanHeroAttack(matchViewSeat)==null;heroAttack.Click+=(s,e)=>BeginHeroAttack();actions.Children.Add(heroAttack);var placement=Btn("位",18);placement.Height=18;placement.FontSize=9;placement.Padding=new Thickness(0);placement.ToolTip=choosePosition?"关闭随从位置选择":"开启随从位置选择";placement.Background=choosePosition?B("#EDF4F0"):B("#FFFFFF");placement.IsEnabled=match.MulliganComplete&&CanMatchInput();placement.Click+=(s,e)=>TogglePlacement();actions.Children.Add(placement);var cancel=Btn("取消",34);cancel.Height=18;cancel.Click+=(s,e)=>{ClearPending();inspectMatch=false;RenderMatch();};actions.Children.Add(cancel);var fresh=Btn(lanMode?"房间":"新局",34);fresh.Height=18;fresh.Click+=(s,e)=>{if(lanMode)ShowPage("lan");else{RefreshLobbyDecks();ShowPage("lobby");}};actions.Children.Add(fresh);var end=Btn("结束",34);end.Height=18;end.Foreground=Ink;end.IsEnabled=match.MulliganComplete&&CanMatchInput();end.Click+=(s,e)=>DoMatch("end");actions.Children.Add(end);Grid.SetColumn(actions,1);heading.Children.Add(actions);livePanel.Children.Add(heading);
  int other=1-matchViewSeat;Put(livePanel,LiveHero(other,false),1);Put(livePanel,LiveBoard(other),2);Put(livePanel,new Border{Background=Line,Height=1,VerticalAlignment=VerticalAlignment.Center},3);Put(livePanel,LiveBoard(matchViewSeat),4);Put(livePanel,LiveHero(matchViewSeat,true),5);Put(livePanel,testTakeOpen&&localTest&&!lanMode&&match.TestMode?LiveTestTake():inspectMatch?LiveInspection():LiveHand(),6);if(!match.MulliganComplete||emoteOpen||ChoicePending()){foreach(UIElement child in livePanel.Children)if(Grid.GetRow(child)==6)child.Visibility=Visibility.Collapsed;Put(livePanel,new ScrollViewer{Content=!match.MulliganComplete?MulliganOverlay():emoteOpen?EmoteOverlay():ChoiceOverlay(),VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled},6);}ApplyFonts(livePanel);RefreshRecords();PresentMatchVisuals();RefreshAnimationWait();
  if(awaitHandoff)ShowHandoff();
 }
 FrameworkElement MulliganOverlay(){var p=match.Players[matchViewSeat];var outer=new Grid();outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(20)});outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(14)});var cards=new StackPanel{Orientation=Orientation.Horizontal};foreach(var hand in p.Hand){var card=match.Card(hand.CardId);var item=Btn(card.Cost+"费 · "+card.Name,Math.Max(20,(Width-38)/Math.Max(1,p.Hand.Count)-2));item.Height=19;item.FontSize=9;item.Margin=new Thickness(1,0,1,0);item.Padding=new Thickness(1,0,1,0);item.ToolTip=card.Name+" · 点击选择换牌";item.Background=selectedMulligan.Contains(hand.Id)?B("#DCE9E0"):B("#FFFFFF");item.IsEnabled=CanMatchInput()&&!p.MulliganDone;item.Click+=(a,b)=>{if(selectedMulligan.Contains(hand.Id))selectedMulligan.Remove(hand.Id);else selectedMulligan.Add(hand.Id);RenderMatch();};cards.Children.Add(item);}outer.Children.Add(cards);var confirm=Btn(p.MulliganDone?"已确认 · 等待对方":"确认换牌（"+selectedMulligan.Count+" 张）",130);confirm.Height=14;confirm.FontSize=8;confirm.Padding=new Thickness(0);confirm.IsEnabled=CanMatchInput()&&!p.MulliganDone;confirm.Click+=(a,b)=>{int[] ids=selectedMulligan.ToArray();selectedMulligan.Clear();DoMatch("mulligan",selectedIds:ids);};Grid.SetRow(confirm,1);outer.Children.Add(confirm);return outer;}
 FrameworkElement EmoteOverlay(){var outer=new Grid();outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(12)});outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(14)});outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(14)});outer.RowDefinitions.Add(new RowDefinition{Height=new GridLength(14)});var head=new Grid();head.ColumnDefinitions.Add(new ColumnDefinition());head.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});head.Children.Add(T("英雄对话 · "+HeroEmotes.Name(match.Players[matchViewSeat].ClassId),9,Muted));var close=Btn("×",18);close.Height=12;close.FontSize=9;close.Padding=new Thickness(0);close.Click+=(a,b)=>{emoteOpen=false;RenderMatch();};Grid.SetColumn(close,1);head.Children.Add(close);Grid.SetColumnSpan(head,2);outer.Children.Add(head);var options=HeroEmotes.Options(match.Players[matchViewSeat].ClassId);for(int index=0;index<options.Length;index++){var option=options[index];var button=Btn(option.Key,52);button.Height=13;button.FontSize=9;button.Padding=new Thickness(1,0,1,0);button.ToolTip=option.Value;button.IsEnabled=!match.Finished&&(!lanMode||lanReady&&!lanWaiting);button.Click+=(a,b)=>{emoteOpen=false;DoMatch("emote",emote:option.Value);};var cell=new Border{Child=button,Margin=new Thickness(1,0,1,1),Background=B("#FFFFFF"),BorderBrush=Line,BorderThickness=new Thickness(1)};Grid.SetColumn(cell,index<3?0:1);Grid.SetRow(cell,1+index%3);if(index==0){outer.ColumnDefinitions.Add(new ColumnDefinition());outer.ColumnDefinitions.Add(new ColumnDefinition());}outer.Children.Add(cell);}return outer;}
 string PendingHint(){if(ChoicePending())return "选择一项抉择 · 右键取消，手牌保留";if(NeedsPlacement())return "选左 / 右，或点空槽";return pending=="attack"||pending=="heroattack"?"点击敌方随从或英雄":pending=="power"?"选择英雄技能目标":pending=="play"?(match.Card(match.Players[matchViewSeat].Hand.First(h=>h.Id==pendingId).CardId).Type=="MINION"&&pendingPosition<0?"点击己方空槽，或选择战吼目标":"选择目标"):"";}
 string HeroWeaponLabel(int seat){var p=match.Players[seat];int attack=match.HeroAttack(seat);if(p.Frozen&&fullEffects&&!minimal)return "冻结 · 不能攻击";if(minimal)return "武"+(attack>0?" "+attack:"");return p.WeaponDurability>0?match.Card(p.WeaponId).Name+" "+attack+"/"+p.WeaponDurability:attack>0?"攻击 · "+attack:"武器 · 空";}
 void UseWeaponSlot(int seat,bool own){if(own&&match.HeroAttack(seat)>0)BeginHeroAttack();else if(match.Players[seat].WeaponId!=null)InspectMatchCard(match.Card(match.Players[seat].WeaponId));else status.Text="英雄当前没有攻击力。";}
 FrameworkElement LiveHero(int seat,bool own){var p=match.Players[seat];var grid=new Grid();grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(minimal?15:28)});grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(minimal?9:14)});var boxes=new Grid();boxes.ColumnDefinitions.Add(new ColumnDefinition());boxes.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1.4,GridUnitType.Star)});boxes.ColumnDefinitions.Add(new ColumnDefinition());
  var w=MatchBox(HeroWeaponLabel(seat),()=>UseWeaponSlot(seat,own));if(p.Frozen&&fullEffects&&!minimal)((TextBlock)w.Child).Foreground=FrozenMarkerBrush();w.ToolTip=p.Frozen?"英雄被冻结，不能攻击；英雄技能仍可使用。":HeroWeaponLabel(seat);boxes.Children.Add(w);
  var hero=MatchBox(minimal?Math.Max(0,p.Health).ToString():(own?"我方":"对方")+" · "+ClassLabel(p.ClassId)+"  "+Math.Max(0,p.Health)+" / 甲"+p.Armor,()=>{if(pending!="")ClickMatchTarget(new MatchTarget(seat));});hero.PreviewMouseRightButtonDown+=(s,e)=>{e.Handled=true;if(own&&!minimal&&pending==""&&match.MulliganComplete&&!match.Finished&&!match.AnimationPlaying&&(!lanMode||lanReady&&!lanWaiting)){emoteOpen=true;inspectMatch=false;testTakeOpen=false;RenderMatch();}};Grid.SetColumn(hero,1);boxes.Children.Add(hero);RegisterVisualTarget(seat,0,hero);
  var power=MatchBox(minimal?"技":"英雄技能 · 2费"+(p.PowerUsed?" · 已用":""),()=>{if(own)BeginPower();else status.Text="对方英雄技能。";});power.Opacity=p.PowerUsed?.5:1;Grid.SetColumn(power,2);boxes.Children.Add(power);grid.Children.Add(boxes);
  var resources=new Grid();resources.ColumnDefinitions.Add(new ColumnDefinition());resources.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var resourceText=T(OverloadRules.ResourceLabel(p,minimal)+(!own?" · 手牌 "+p.HandCount:""),9,Muted);if(!own)enemyHandStatus=resourceText;resources.Children.Add(resourceText);var mana=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};for(int n=0;n<10;n++){var mark=new Border{Width=minimal?5:7,Height=minimal?5:7,Margin=new Thickness(1,0,0,0),Background=OverloadRules.IsFilled(p,n)?B("#B5C8BB"):B("#FFFFFF"),BorderBrush=n<p.MaxMana||OverloadRules.IsFilled(p,n)?B("#A5B9AC"):Line,BorderThickness=new Thickness(1)};if(OverloadRules.IsLocked(p,n)){mark.ToolTip="本回合过载锁定";var cross=new Grid();cross.Children.Add(new System.Windows.Shapes.Line{X1=0,Y1=0,X2=minimal?3:5,Y2=minimal?3:5,Stroke=Muted,StrokeThickness=.7});cross.Children.Add(new System.Windows.Shapes.Line{X1=minimal?3:5,Y1=0,X2=0,Y2=minimal?3:5,Stroke=Muted,StrokeThickness=.7});mark.Child=cross;}mana.Children.Add(mark);}Grid.SetColumn(mana,1);resources.Children.Add(mana);Put(grid,resources,1);return grid;}
 Border MatchBox(string text,Action click){var label=T(text,10,Ink);label.TextAlignment=TextAlignment.Center;label.TextTrimming=TextTrimming.CharacterEllipsis;var box=new Border{Child=label,Background=B("#F7F8FA"),BorderBrush=Line,BorderThickness=new Thickness(1),Margin=new Thickness(0,0,3,0),Cursor=Cursors.Hand,CornerRadius=new CornerRadius(codex?2:0)};box.MouseLeftButtonDown+=(s,e)=>click();return box;}
 FrameworkElement LiveBoard(int seat){var strip=new Grid{Margin=new Thickness(0,1,0,1)};for(int n=0;n<7;n++)strip.ColumnDefinitions.Add(new ColumnDefinition());var board=match.Players[seat].Board;
  for(int n=0;n<7;n++){int place=n;var border=new Border{Height=minimal?51:84,VerticalAlignment=VerticalAlignment.Top,Background=B("#FFFFFF"),BorderBrush=Line,BorderThickness=new Thickness(1),Margin=new Thickness(0,0,n==6?0:2,0),CornerRadius=new CornerRadius(codex?3:0),Cursor=Cursors.Hand};Grid.SetColumn(border,n);strip.Children.Add(border);if(n>=board.Count){border.Background=B("#FAFBFC");border.MouseLeftButtonDown+=(s,e)=>ClickEmptySlot(seat,place);continue;}var unit=board[n];liveUnits.Add(border);border.Tag=unit.Id;RegisterVisualTarget(seat,unit.Id,border);
   var cell=new Grid{Margin=new Thickness(1,1,1,1)};cell.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(12)});cell.ColumnDefinitions.Add(new ColumnDefinition());cell.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(12)});var attack=T(match.AttackValue(unit).ToString(),10,UnitAttackBrush(unit));attack.TextAlignment=TextAlignment.Center;cell.Children.Add(attack);var label=new StackPanel{VerticalAlignment=VerticalAlignment.Center};if(!minimal){var name=T(match.Card(unit.CardId).Name,10,fullEffects&&match.Card(unit.CardId).Rarity=="LEGENDARY"?B(codex&&dark?"#C5AA68":"#94732D"):Ink);name.TextAlignment=TextAlignment.Center;name.TextWrapping=TextWrapping.Wrap;name.LineHeight=11;label.Children.Add(name);}var effects=ColoredUnitTags(unit);effects.TextWrapping=TextWrapping.Wrap;effects.TextAlignment=TextAlignment.Center;effects.LineHeight=10;label.Children.Add(effects);var dot=Btn("⋯",13);dot.Height=9;dot.FontSize=9;dot.Padding=new Thickness(0);dot.Click+=(s,e)=>InspectMatchCard(match.Card(unit.CardId),unit);label.Children.Add(dot);Grid.SetColumn(label,1);cell.Children.Add(label);var hp=T(unit.Health.ToString(),10,UnitHealthBrush(unit));hp.TextAlignment=TextAlignment.Center;Grid.SetColumn(hp,2);cell.Children.Add(hp);border.Child=cell;if(seat==matchViewSeat&&NeedsPlacement()){border.Child=null;var wrapper=new Grid();wrapper.RowDefinitions.Add(new RowDefinition());wrapper.RowDefinitions.Add(new RowDefinition{Height=new GridLength(12)});wrapper.Children.Add(cell);var choices=new Grid();choices.ColumnDefinitions.Add(new ColumnDefinition());choices.ColumnDefinitions.Add(new ColumnDefinition());for(int side=0;side<2;side++){bool rightSide=side==1;var pick=Btn(rightSide?"右":"左",16);pick.Height=12;pick.FontSize=9;pick.Padding=new Thickness(0);pick.Margin=new Thickness(0);pick.ToolTip="放在"+match.Card(unit.CardId).Name+"的"+(rightSide?"右侧":"左侧");pick.Click+=(s,e)=>{e.Handled=true;ClickRelativeSlot(seat,unit.Id,rightSide);};Grid.SetColumn(pick,side);choices.Children.Add(pick);placementButtons.Add(pick);}Put(wrapper,choices,1);border.Child=wrapper;}
   if((pending=="attack"&&pendingId==unit.Id))border.Background=B("#EDF4F0");else if(seat==matchViewSeat&&match.CanAttack(seat,unit)==null)border.BorderBrush=B("#A5B9AC");border.MouseLeftButtonDown+=(s,e)=>ClickMatchTarget(new MatchTarget(seat,unit.Id));
  }return strip;
 }
 System.Windows.Media.Brush UnitAttackBrush(BattleUnit unit){return fullEffects&&!minimal&&match.AttackValue(unit)>unit.BaseAttack?B(codex&&dark?"#85BC91":"#387C60"):Ink;}
 System.Windows.Media.Brush UnitHealthBrush(BattleUnit unit){return fullEffects&&!minimal&&unit.DamageTaken>0&&unit.Health<unit.MaxHealth?B(codex&&dark?"#D78B86":"#B04B46"):Ink;}
 System.Windows.Media.Brush FrozenMarkerBrush(){return B(codex&&dark?"#8FCBD8":"#3F859D");}
 TextBlock ColoredUnitTags(BattleUnit unit){var text=T("",9,Muted);var tags=UnitTags(unit).Split(' ');for(int i=0;i<tags.Length;i++){if(i>0)text.Inlines.Add(new Run(" "));var run=new Run(tags[i]);if(fullEffects&&!minimal&&match.IsEnraged(unit)&&(tags[i]=="激怒"||tags[i]=="激"))run.Foreground=B(codex&&dark?"#D78B86":"#B04B46");if(fullEffects&&!minimal&&unit.Frozen&&tags[i]=="冻结")run.Foreground=FrozenMarkerBrush();text.Inlines.Add(run);}return text;}
 string UnitTags(BattleUnit unit){var tags=new List<string>();if(unit.Frozen)tags.Add("冻结");if(unit.Taunt)tags.Add("嘲讽");if(unit.Shield)tags.Add("圣盾");if(match.HasWindfury(unit))tags.Add("风怒");if(match.IsEnraged(unit))tags.Add("激怒");if(match.HasCharge(unit))tags.Add("冲锋");if(unit.Poison)tags.Add("剧毒");if(unit.Stealth)tags.Add("潜行");var card=match.Card(unit.CardId);if(unit.ForestDeathrattles>0)tags.Add("亡语");if(!unit.Silenced){if(MatchEngine.Has(card,"DEATHRATTLE")&&!tags.Contains("亡语"))tags.Add("亡语");if(MatchEngine.Has(card,"ELUSIVE"))tags.Add("扰魔");if(MatchEngine.Has(card,"AURA"))tags.Add("光环");if(MatchEngine.Has(card,"CANT_ATTACK"))tags.Add("禁攻");if(card.BaseId=="CS2_033")tags.Add("冻伤");if(card.BaseId=="NEW1_009")tags.Add("治疗");}if(unit.SpellDamage>0)tags.Add((minimal?"法":"法强+")+unit.SpellDamage);if(minimal&&tags.Count>3)tags=tags.Select(t=>t=="光环"?"环":t.StartsWith("法")?"法"+unit.SpellDamage:t=="冻伤"?"寒":t=="治疗"?"愈":t.Substring(0,1)).ToList();return tags.Count==0?"—":String.Join(" ",tags);}
 FrameworkElement LiveHand(){var grid=new Grid();grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(11)});grid.RowDefinitions.Add(new RowDefinition());var p=match.Players[matchViewSeat];deckCountText=T("手牌 "+p.Hand.Count+" · 牌库 "+p.Deck.Count,9,Muted);grid.Children.Add(deckCountText);handCardVisuals.Clear();var cards=new StackPanel{Orientation=Orientation.Horizontal};var scroll=new ScrollViewer{Content=cards,HorizontalScrollBarVisibility=ScrollBarVisibility.Hidden,VerticalScrollBarVisibility=ScrollBarVisibility.Disabled};liveHandScroll=scroll;double restore=matchHandScroll;scroll.Loaded+=(s,e)=>scroll.ScrollToHorizontalOffset(restore);scroll.ScrollChanged+=(s,e)=>{if(e.HorizontalChange!=0)matchHandScroll=scroll.HorizontalOffset;};scroll.PreviewMouseWheel+=(s,e)=>{if(scroll.ScrollableWidth>0){scroll.ScrollToHorizontalOffset(scroll.HorizontalOffset-e.Delta);e.Handled=true;}};Put(grid,scroll,1);
  foreach(var hand in p.Hand){var card=match.Card(hand.CardId);var inner=new Grid();inner.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(13)});inner.ColumnDefinitions.Add(new ColumnDefinition());inner.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(12)});var cost=T(match.CardCost(matchViewSeat,card).ToString(),10,Muted);cost.TextAlignment=TextAlignment.Center;inner.Children.Add(cost);var title=T(minimal?(card.Type=="SPELL"?"法":card.Type=="WEAPON"?"武":"随"):card.Name,10,Ink);title.TextTrimming=TextTrimming.CharacterEllipsis;Grid.SetColumn(title,1);inner.Children.Add(title);var dot=Btn("⋯",12);dot.Height=19;dot.FontSize=9;dot.Padding=new Thickness(0);dot.Click+=(s,e)=>InspectMatchCard(card);Grid.SetColumn(dot,2);inner.Children.Add(dot);var border=new Border{Child=inner,Width=minimal?57:105,Height=22,Background=pending=="play"&&pendingId==hand.Id?B("#EDF4F0"):B("#FFFFFF"),BorderBrush=Line,BorderThickness=new Thickness(1),Margin=new Thickness(0,0,3,0),Cursor=Cursors.Hand,ToolTip=pending=="play"&&pendingId==hand.Id?"右键取消出牌":""};border.PreviewMouseRightButtonDown+=(s,e)=>{e.Handled=true;if(pending=="play"&&pendingId==hand.Id)CancelPendingPlay();};border.MouseLeftButtonDown+=(s,e)=>BeginCard(hand.Id);handCardVisuals[hand.Id]=border;cards.Children.Add(border);}return grid;
 }
 FrameworkElement LiveInspection(){var stack=new StackPanel{Margin=new Thickness(4,0,4,0)};var header=new Grid{Height=13};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(60)});var title=T(inspectedCard.Name,10,Ink);title.TextTrimming=TextTrimming.CharacterEllipsis;header.Children.Add(title);var back=Btn("返回手牌",60);back.HorizontalAlignment=HorizontalAlignment.Right;back.Height=13;back.FontSize=9;back.Click+=(s,e)=>{inspectMatch=false;RenderMatch();};Grid.SetColumn(back,1);header.Children.Add(back);stack.Children.Add(header);var text=T((match.Players[matchViewSeat].Hand.Any(h=>h.CardId==inspectedCard.Id)?"当前费用 "+match.CardCost(matchViewSeat,inspectedCard)+" · ":"")+CardDetailMetadata(inspectedCard)+Environment.NewLine+(inspectedCard.Text.Length>0?inspectedCard.Text:"无特殊效果。")+ForestDetail(),9,Muted);text.TextWrapping=TextWrapping.Wrap;stack.Children.Add(text);return new Border{Background=B("#F7F8FA"),BorderBrush=Line,BorderThickness=new Thickness(1),Child=new ScrollViewer{Content=stack,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}};}
 string ForestDetail(){var unit=match.Players.SelectMany(p=>p.Board).FirstOrDefault(u=>u.Id==inspectedUnitId);return unit!=null&&unit.ForestDeathrattles>0?Environment.NewLine+"附加亡语 ×"+unit.ForestDeathrattles+"：召唤一个2/2的树人。":"";}
 void InspectMatchCard(CardRecord card,BattleUnit unit=null){inspectedUnitId=unit==null?0:unit.Id;inspectedCard=card;inspectMatch=true;RenderMatch();}
 void CancelPendingPlay(){if(!CanMatchInput()||pending!="play")return;ClearPending();inspectMatch=false;RenderMatch();status.Text="已取消出牌，手牌保留。";}
 bool ChoicePending(){if(pending!="play"||match==null)return false;var hand=match.Players[matchViewSeat].Hand.FirstOrDefault(h=>h.Id==pendingId);if(hand==null)return false;var card=match.Card(hand.CardId);return match.Rules.IsChoice(card)&&pendingChoice==null&&(card.Type!="MINION"||pendingPosition>=0);}
 FrameworkElement ChoiceOverlay(){var hand=match.Players[matchViewSeat].Hand.First(h=>h.Id==pendingId);var options=match.Rules.Choices(match.Card(hand.CardId));var grid=new Grid();Grid.SetRow(grid,6);grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition());for(int n=0;n<options.Length;n++){var option=options[n];var title=T(option.Title,10,Ink);title.TextWrapping=TextWrapping.Wrap;title.TextAlignment=TextAlignment.Center;var tile=new Border{Child=title,Background=B("#F7F8FA"),BorderBrush=Line,BorderThickness=new Thickness(1),Margin=new Thickness(2),Padding=new Thickness(3),ToolTip=option.Description+" · 右键取消",Cursor=Cursors.Hand};tile.MouseLeftButtonDown+=(s,e)=>{e.Handled=true;SelectChoice(option.Key);};tile.PreviewMouseRightButtonDown+=(s,e)=>{e.Handled=true;CancelPendingPlay();};Grid.SetColumn(tile,n);grid.Children.Add(tile);}return grid;}

 void SelectChoice(string choice){if(!CanMatchInput()||pending!="play")return;var hand=match.Players[matchViewSeat].Hand.FirstOrDefault(h=>h.Id==pendingId);if(hand==null)return;var card=match.Card(hand.CardId);if(!match.Rules.ValidChoice(card,choice))return;pendingChoice=choice;string target=match.Rules.Target(card,choice,ComboRules.Active(match));if(target!="NONE"&&!match.HasTargets(matchViewSeat,target,card.Type=="SPELL")){if(card.Type=="SPELL"){status.Text="当前没有符合条件的目标；可右键取消出牌。";pendingChoice=null;RenderMatch();return;}if(pendingPosition<0){status.Text="请选择随从位置。";RenderMatch();return;}DoMatch("play",pendingId,null,pendingPosition,pendingChoice);return;}if(card.Type=="MINION"&&pendingPosition<0){status.Text="请选择己方空槽或位置。";RenderMatch();return;}if(target=="NONE")DoMatch("play",pendingId,null,pendingPosition,pendingChoice);else{status.Text="请选择目标；右键取消出牌，牌留在手中。";RenderMatch();}}
 void BeginCard(int handId){if(!CanMatchInput()||!match.MulliganComplete)return;var hand=match.Players[matchViewSeat].Hand.First(h=>h.Id==handId);var card=match.Card(hand.CardId);if(!match.CanUseCard(matchViewSeat,card)){status.Text="只能使用本职业或中立卡牌。";return;}if(!match.Rules.Supports(card)){status.Text="该卡效果尚未实现。";return;}if(match.Players[matchViewSeat].Mana<match.CardCost(matchViewSeat,card)){status.Text="法力不足。";return;}if(card.Type=="MINION"&&match.Players[matchViewSeat].Board.Count>=7){status.Text="战场已满七个随从。";return;}pending="play";pendingId=handId;pendingPosition=-1;pendingChoice=null;inspectMatch=false;var effect=match.Rules.Effect(card);if(card.Type!="MINION"&&match.Rules.Target(card,null,ComboRules.Active(match))=="NONE"&&!match.Rules.IsChoice(card))DoMatch("play",handId);else RenderMatch();}
 void ClickEmptySlot(int seat,int position){if(!CanMatchInput()||pending!="play"||seat!=matchViewSeat)return;var hand=match.Players[seat].Hand.FirstOrDefault(h=>h.Id==pendingId);if(hand==null)return;var card=match.Card(hand.CardId);if(card.Type!="MINION")return;pendingPosition=Math.Min(position,match.Players[seat].Board.Count);if(match.Rules.IsChoice(card)&&pendingChoice==null){RenderMatch();return;}string target=match.Rules.Target(card,pendingChoice,ComboRules.Active(match));if(target=="NONE"||!match.HasTargets(seat,target,false))DoMatch("play",pendingId,null,pendingPosition,pendingChoice);else RenderMatch();}
 void ClickMatchTarget(MatchTarget target){if(!CanMatchInput()||!match.MulliganComplete)return;
  if(pending=="play"){var hand=match.Players[matchViewSeat].Hand.FirstOrDefault(h=>h.Id==pendingId);if(hand==null){ClearPending();RenderMatch();return;}var card=match.Card(hand.CardId);if(match.Rules.IsChoice(card)&&pendingChoice==null){status.Text=card.Type=="MINION"&&pendingPosition<0?"先选己方空槽，再选择一项抉择。":"请先从两张抉择卡中选一张。";return;}if(NeedsPlacement()){status.Text="先点击己方随从下方的左 / 右，或点击空槽。";return;}string targetMask=match.Rules.Target(card,pendingChoice,ComboRules.Active(match));if(targetMask=="NONE"){status.Text="请选择己方空槽召唤随从。";return;}DoMatch("play",pendingId,target,pendingPosition,pendingChoice);return;}
  if(pending=="power"){DoMatch("power",0,target);return;}
  if((pending=="attack"||pending=="heroattack")&&target.Seat!=matchViewSeat){DoMatch("attack",pending=="heroattack"?0:pendingId,target);return;}
  if((pending=="attack"||pending=="heroattack")&&target.Seat==matchViewSeat&&target.Hero){BeginHeroAttack();return;}
  if(target.Seat==matchViewSeat&&!target.Hero){var unit=match.Unit(target);string error=match.CanAttack(matchViewSeat,unit);if(error!=null){status.Text=error;return;}pending=pending=="attack"&&pendingId==target.UnitId?"":"attack";pendingId=target.UnitId;inspectMatch=false;RenderMatch();}else status.Text="先点击己方随从或手牌。";
 }
 void BeginHeroAttack(){if(!CanMatchInput()||!match.MulliganComplete)return;string error=match.CanHeroAttack(matchViewSeat);if(error!=null){status.Text=error;return;}pending="heroattack";pendingId=0;inspectMatch=false;RenderMatch();}
 void BeginPower(){if(!CanMatchInput()||!match.MulliganComplete)return;var player=match.Players[matchViewSeat];if(player.PowerUsed){status.Text="本回合已使用英雄技能。";return;}if(player.Mana<2){status.Text="英雄技能需要两点法力。";return;}if(match.PowerNeedsTarget(matchViewSeat)){pending="power";inspectMatch=false;RenderMatch();}else DoMatch("power");}
 void ApplyMatchAction(ActionResult result){if(result.Success){ClearPending();inspectMatch=false;testTakeOpen=false;RenderMatch();Record(match.Log.LastOrDefault()??"操作完成");}status.Text=match!=null&&match.AnimationPlaying?"正在播放动画 · 暂停操作":result.Message;}
 void ShowMatchResult(ActionResult result){status.Text=match!=null&&match.AnimationPlaying?"正在播放动画 · 暂停操作":result.Message;}
 void ShowHandoff(){var cover=new Border{Background=B("#FFFFFF"),BorderBrush=Line,BorderThickness=new Thickness(1),Margin=new Thickness(12,18,12,18)};Grid.SetRow(cover,1);Grid.SetRowSpan(cover,6);var stack=new StackPanel{VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Center};stack.Children.Add(T("请交给玩家 "+(handoffSeat+1),12,Ink));var button=Btn("继续",80);button.Margin=new Thickness(0,12,0,0);button.Click+=(s,e)=>{awaitHandoff=false;matchViewSeat=handoffSeat;matchHandScroll=0;selectedMulligan.Clear();ClearPending();RenderMatch();};stack.Children.Add(button);cover.Child=stack;livePanel.Children.Add(cover);}
}
}
