using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
namespace Touchfish {
public partial class PanelWindow {
 public void PreviewRogueScope(string folder){
  previewRun=true;Directory.CreateDirectory(folder);int before=checks;var all=catalog.Deckable(catalog.Pool("classic-2014"));Check(all.Where(c=>c.CardClass=="ROGUE").Count()==25&&all.Where(c=>c.CardClass=="ROGUE").All(c=>matchRules.Supports(c)),"All 25 Rogue cards supported");
  var g=MatchFixture("ROGUE");int prep=Inject(g,"EX1_145");g.Play(0,prep);int blade=Inject(g,"CS2_233");Check(g.HandCost(0,g.Players[0].Hand.Single(h=>h.Id==blade))==0,"Preparation discounts next spell by three");Check(!g.Play(0,blade).Success&&g.Players[0].PreparationDiscount==3,"Rejected spell preserves preparation");g.EquipRaw(0,"GAME_DAGGER",3,2,false);g.Summon(0,"VAN_EX1_563");var enemy=g.Summon(1,"VAN_CS2_182");Check(g.Play(0,blade).Success&&g.Players[0].Mana==10&&g.Players[0].WeaponId==null&&g.Players[1].Health==22&&g.Players[1].Board.Count==0&&g.Players[0].PreparationDiscount==0,"Blade Flurry destroys weapon and hits all enemies with spell power using preparation");
  g=MatchFixture("ROGUE");g.Play(0,Inject(g,"EX1_145"));g.Play(0,Inject(g,"CS2_231"));Check(g.Players[0].PreparationDiscount==3,"Minion play does not consume preparation");g.EndTurn();Check(g.Players[0].PreparationDiscount==0,"Preparation expires at turn end");
  g=MatchFixture("ROGUE");var unit=g.Summon(0,"VAN_CS2_182");g.Buff(new MatchTarget(0,unit.Id),2,2);g.Play(0,Inject(g,"EX1_144"),new MatchTarget(0,unit.Id));var bounced=g.Players[0].Hand.Single();Check(bounced.CostAdjustment==-2&&g.HandCost(0,bounced)==2&&g.Players[0].Board.Count==0,"Shadowstep discounts returned instance by two");int ordinary=Inject(g,"CS2_182");Check(g.HandCost(0,g.Players[0].Hand.Single(h=>h.Id==ordinary))==4,"Same-name ordinary copy retains separate cost");g.Summon(0,"VAN_EX1_315");Check(g.HandCost(0,bounced)==1,"Shadowstep discount combines correctly with portal floor");g.Silence(new MatchTarget(0,g.Players[0].Board.Single().Id));int mana=g.Players[0].Mana;g.Play(0,bounced.Id);Check(g.Players[0].Mana==mana-2&&g.Players[0].Board.Last().BaseAttack==4&&g.Players[0].Board.Last().MaxHealth==5,"Returned card pays adjusted cost and resets board enchantments");
  g=MatchFixture("ROGUE");unit=g.Summon(0,"VAN_CS2_182");var natural=g.Summon(0,"VAN_EX1_522");g.Play(0,Inject(g,"EX1_128"));Check(unit.Stealth&&natural.Stealth,"Conceal grants stealth to existing friendly minions");g.EndTurn();Check(unit.Stealth,"Conceal lasts through opponent turn");g.EndTurn();Check(!unit.Stealth&&natural.Stealth,"Conceal expires on caster turn without removing natural stealth");g.Play(0,Inject(g,"NEW1_014"),new MatchTarget(0,unit.Id));g.EndTurn();g.EndTurn();Check(unit.Stealth,"Master of Disguise grants permanent stealth");
  g=MatchFixture("ROGUE");var left=g.Summon(1,"VAN_CS2_182");var middle=g.Summon(1,"VAN_EX1_522");var right=g.Summon(1,"VAN_CS2_182");middle.Stealth=false;g.Summon(0,"VAN_EX1_563");g.Play(0,Inject(g,"EX1_126"),new MatchTarget(1,middle.Id));Check(g.Players[1].Board.Count==1&&g.Players[1].Board[0].Id==middle.Id&&middle.AttacksUsed==0&&g.Players[1].Health==30,"Betrayal uses source poison on neighbors without retaliation or spell power");
  g=MatchFixture("ROGUE");unit=g.Summon(0,"VAN_EX1_522");unit.SummonTurn=0;enemy=g.Summon(1,"VAN_CS2_182");Check(g.Attack(0,unit.Id,new MatchTarget(1,enemy.Id)).Success&&g.Players[1].Board.Count==0,"Patient Assassin destroys damaged minion");g=MatchFixture("ROGUE");unit=g.Summon(0,"VAN_EX1_522");unit.SummonTurn=0;g.Silence(new MatchTarget(0,unit.Id));enemy=g.Summon(1,"VAN_CS2_182");g.Attack(0,unit.Id,new MatchTarget(1,enemy.Id));Check(g.Players[1].Board.Count==1&&enemy.Health==4,"Silence removes Assassin poison");
  g=MatchFixture("ROGUE");unit=g.Summon(0,"VAN_CS2_182");enemy=g.Summon(1,"VAN_CS2_182");g.Play(0,Inject(g,"NEW1_004"));Check(g.Players.All(p=>p.Board.Count==0)&&g.Players[0].Hand.Count==1&&g.Players[1].Hand.Count==1&&g.Graveyard.All(e=>e.Reason!=GraveyardReason.MinionDied),"Vanish returns both boards without deaths when hands have room");
  g=MatchFixture("ROGUE");for(int n=0;n<10;n++)Inject(g,"CS2_231",1);enemy=g.Summon(1,"VAN_EX1_556");g.Play(0,Inject(g,"NEW1_004"));Check(g.Players[1].Board.Single().CardId=="VAN_skele21"&&g.GraveyardFor(1,GraveyardReason.MinionDied).Length==1,"Full-hand Vanish destroys minion and resolves its deathrattle without returning new token");
  g=MatchFixture();Check(g.Play(0,Inject(g,"NEW1_017")).Success&&g.Players[0].Board.Single().BaseAttack==1,"Hungry Crab can be played without Murloc target");g=MatchFixture();enemy=g.Summon(1,"VAN_EX1_506a");enemy.Shield=true;g.Play(0,Inject(g,"NEW1_017"),new MatchTarget(1,enemy.Id));unit=g.Players[0].Board.Single();Check(g.Players[1].Board.Count==0&&g.AttackValue(unit)==3&&unit.MaxHealth==4&&g.GraveyardFor(1,GraveyardReason.MinionDied).Length==1,"Hungry Crab destroys shielded Murloc and gains two/two");g=MatchFixture();enemy=g.Summon(1,"VAN_CS2_182");int crab=Inject(g,"NEW1_017");Check(!g.Play(0,crab,new MatchTarget(1,enemy.Id)).Success&&g.Players[0].Mana==10&&g.Players[0].Hand.Count==1,"Non-Murloc target rejected atomically");
  VerifyRogueTcp(folder);var coverage=all.Select(c=>new{Id=c.Id,Name=c.Name,Supported=matchRules.Supports(c)}).ToArray();JsonData.Write(Path.Combine(folder,"match-rule-coverage.json"),new{SupportedCards=coverage.Count(c=>c.Supported),TotalCards=382,Cards=coverage,Scope="Rogue and Hungry Crab focused verification"});File.WriteAllText(Path.Combine(folder,"rogue-verification.txt"),"PASS: "+(checks-before)+" targeted Rogue/Hungry Crab assertions, instance costs, preparation, stealth, poison, full-hand bounce, graveyard, real loopback TCP and WPF previews.");
 }
 void VerifyRogueTcp(string folder){
  LeaveLan();ApplyTheme(true,true);ApplyMode(false);SetFullEffects(false);var guest=new PanelWindow(true){ShowInTaskbar=false,Opacity=0};guest.Show();guest.ApplyMode(false);guest.ApplyTheme(true,true);try{lanPort.Text=FreeLanPort().ToString();lanDeck.SelectedIndex=0;lanClass.SelectedItem=Classes.First(c=>c.Key=="MAGE");BeginLan(true);guest.lanDeck.SelectedIndex=0;guest.lanClass.SelectedItem=Classes.First(c=>c.Key=="ROGUE");guest.lanAddress.Text="127.0.0.1:"+lanPort.Text;guest.BeginLan(false);PumpLan(()=>lanReady&&guest.lanReady,"Rogue TCP peers connect");DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>guest.match.Players[0].MulliganDone,"Host mulligan reaches guest");guest.DoMatch("mulligan",selectedIds:new int[0]);PumpLan(()=>match.MulliganComplete&&!guest.lanWaiting,"Guest mulligan starts game");DoMatch("end");PumpLan(()=>guest.match.Active==1,"Guest rogue turn starts");var g=lanAuthority.Game;foreach(var p in g.Players){p.Hand.Clear();p.Board.Clear();}g.Players[1].Mana=10;var body=g.Summon(1,"VAN_CS2_182");int step=Inject(g,"EX1_144",1);int crab=Inject(g,"NEW1_017",1);var fish=g.Summon(0,"VAN_EX1_506a");PublishLan();PumpLan(()=>guest.match.Players[1].Hand.Count==2,"Rogue hand fixture synchronizes");guest.BeginCard(step);guest.ClickMatchTarget(new MatchTarget(1,body.Id));PumpLan(()=>!guest.lanWaiting&&guest.match.Players[1].Hand.Any(h=>h.CostAdjustment==-2),"Shadowstep instance discount synchronizes");var discounted=guest.match.Players[1].Hand.Single(h=>h.CostAdjustment==-2);Check(guest.match.HandCost(1,discounted)==2&&guest.match.Players[0].Hand.Count==0,"Client cost correct and opponent hand masked");guest.InspectMatchCard(guest.match.Card(discounted.CardId),null,discounted);guest.Opacity=1;guest.Render(Path.Combine(folder,"120-shadowstep-details.png"));guest.Opacity=0;guest.inspectMatch=false;guest.BeginCard(crab);guest.ClickEmptySlot(1,0);Check(guest.pending=="play"&&guest.pendingPosition==0,"Crab UI waits for Murloc after placement");guest.ClickMatchTarget(new MatchTarget(0,fish.Id));PumpLan(()=>!guest.lanWaiting&&g.Players[0].Board.Count==0,"Crab battlecry resolves on authority");Check(g.AttackValue(g.Players[1].Board.Single())==3&&guest.match.Players[1].Board.Single().MaxHealth==4,"Crab buffs synchronized");guest.Opacity=1;guest.Render(Path.Combine(folder,"121-hungry-crab-codex.png"));guest.Opacity=0;
  }finally{guest.LeaveLan();guest.Close();LeaveLan();}
 }
}
}
